#!/bin/bash
# =============================================================================== #
#                   I N F O R M A T I O N    N E E D E D                          #
# =============================================================================== #
# This part is where you need to change the values; you need to set your restic
# password (password for the repository), the directory for your repository, 
# the backup directory (by default the backup directory is your Home directory), 
# the destination name of your backup (local, S3, B2, Wasabi, remote host, etc.), 
# your tag (empty by default if used) and your "keep" and "excludes" policies.
# ------------------------------------------------------------------------------- #
#                              R E P O    I N F O                                 #
# ------------------------------------------------------------------------------- #
# You MUST set these values. "KEEP" values CANNOT be left blank; if you are not
# going to use "KEEP" policies the value must be set to "0".
RESTIC_PASSWORD="CHANGE_ME"
RESTIC_REPO="/PATH/TO/YOUR/REPO"
BACKUP_DIR="$HOME"
KEEP_LAST="0"
KEEP_HOURLY="8"
KEEP_DAILY="7"
KEEP_WEEKLY="4"
KEEP_MONTHLY="12"
KEEP_YEARLY="10"

# B2 Credentials
B2_ID=""
B2_KEY=""

# Optional values; The "DESTINATION" value is just use in this script to display
# in the output the name of your destination (e.g.: Google Drive, Amazon, B2, Wasabi, 
# etc.). The "TAG" value will tag your snapshots with any name/tag you want.
# The "CLEAN" value determine when it will execute the forget, prune and check
# commands; this value must be set in days and by default the number 7 means
# it will do these tasks every seven (7) days. These values CAN be left blank
# if you are not planning on use them.
CLEAN="7"
TAG=""
DESTINATION=""

# From v1.7 onwards the exclusion file is located at '.rescript/config' directory

# AFTER THIS LINE YOU DO NOT NEED TO DO ANYTHING ELSE, YOU'RE DONE NOW
# PUT THE SCRIPT TO WORK (remember to give the right to execute with 
# 'chmod 700 rescript') AND GO BACK TO YOUR LIFE
# =============================================================================== #
#                  H E R E   B E G I N S   T H E   S C R I P T
# =============================================================================== #
YELLOW="\033[33m"
ENDCOLOR="\033[0m"
LOCK="$HOME/.rescript/lock/$(basename "$0").lock"
DATEFILE="$HOME/.rescript/config/$(basename "$0")-datefile"
EXCLUDES="$HOME/.rescript/config/$(basename "$0")-exclusions"
SECONDS=0

# Export Password and Repo
export RESTIC_PASSWORD=$RESTIC_PASSWORD
export RESTIC_REPOSITORY=$RESTIC_REPO
export B2_ACCOUNT_ID=$B2_ID
export B2_ACCOUNT_KEY=$B2_KEY

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Create a rescript directories
if [[ ! -d "$HOME/.rescript" ]]; then
  mkdir -p "$HOME/.rescript"
fi
if [[ ! -d "$HOME/.rescript/config" ]]; then
  mkdir -p "$HOME/.rescript/config"
fi
if [[ ! -d "$HOME/.rescript/lock" ]]; then
  mkdir -p "$HOME/.rescript/lock"
fi
if [[ ! -d "$HOME/.rescript/logs" ]]; then
  mkdir -p "$HOME/.rescript/logs"
fi

# For v1.6 and older move the datefile to the [config] directory
if [[ -f "$HOME/.rescript/logs/datefile-$(basename "$0")" ]] ; then
  mv "$HOME/.rescript/logs/datefile-$(basename "$0")" "$HOME/.rescript/config/$(basename "$0")-datefile"
fi

# If there is no exclude file create one
if [[ ! -e "$EXCLUDES" ]] ; then
  touch "$EXCLUDES"
  echo "# These are the default rescript exclusions:" >> "$EXCLUDES"
  echo "$HOME/.cache/*" >> "$EXCLUDES"
  echo "$HOME/.local/share/Trash/*" >> "$EXCLUDES"
  echo "$HOME/.rescript/lock/*" >> "$EXCLUDES"
  echo "$HOME/.Trash" >> "$EXCLUDES"
  echo "$HOME/.Private" >> "$EXCLUDES"
  echo "$HOME/.ecryptfs" >> "$EXCLUDES"
  echo "" >> "$EXCLUDES"
  echo "# Write your custom exclusions below:" >> "$EXCLUDES"
fi
# If there is no date file create one
if [[ ! -z "$CLEAN" ]] ; then
  if [[ ! -e "$DATEFILE" ]]; then
    touch "$DATEFILE"
    date -R > "$DATEFILE"
  fi
fi
# ------------------------------------------------------------------------------- #
Version="rescript-v1.7"
Usage='Author		: Sulfuror, Copyright (c) 2018 <sulfuror@gmail.com>
License		: BSD 2-clause "Simplified" License
Version		: rescript-v1.7
Description	: rescript is a bash script created to manage
		  backups made with restic program.

"restic is a backup program which allows saving multiple revisions 
of files and directories in an encrypted repository 
stored on different backends."

For more information about restic visit https://restic.net

Note that these commands only work when you have already set
the required values correctly.

All restic commands are available within this script except for:
  backup			This will make a backup according to your
				options in this script
  help				This will display rescript help
  version			This wil display the rescript version

For restic help type in you terminal emulator [restic help]. For
other restic commands help you can type:
  restic help [command]
OR
  rescript [restic_command] --help

Commands usage:
  rescript [command] [flags] [options]

Rescript options:
  -b, -backup			Take a snapshot
  -c, -cleanup			Forget and prune [using your policies]
  -d, -deep-check		Check repository with [--read-data] flag
  -e,				Manage exclusions file
	--build			this flag requires one option [home|sys]
				to build an exclusion list based on common
				exclusions patterns, files and directories
	--help			help for [-e]
	edit			this will open your exclusion file
				for you to add, remove or edit your
				exclusion list
	list			list exclusions
  -h, -help			Help for this script
  -m, -mount			Mount your restic repo
  -n, -next-cleanup		Display when it will do the next cleanup
  -u, -unlock			Remove lock created by script [this will
				NOT unlock your repo]
  -r				Restore a snapshot; this option will create
				a folder in your home directory, restore
				the snapshot you want to restore and
				run [--verify] flag
	--help			help for [-r]
	--host			only consider snapshots for this host
				when snapshot-ID is [latest]
	--path			only consider snapshots which include
				this [absolute] path for snapshot-ID [latest]
	--tag			only consider snapshots which include this
				taglist for snapshot-ID [latest]
  -v, -version			Version of this script

Rescript options usage:
  rescript [-o|-option]
For [-e] and [-r]:
  rescript [-e|-r] [option|snapshot-ID]
For [-r] with flags:
  rescript -r [--flag] [option]

For more information about the usage check out the following link:
https://gitlab.com/sulfuror/rescript.sh/blob/master/README.md#usage
'
# ------------------------------------------------------------------------------- #
# Options
while getopts ":bcde:hmnr:uv" o
  do
      case "$o" in
	b|backup)
		if [ -e "$LOCK" ]; then
		  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
		  echo -e "If you are sure $(basename "$0") is not running, type"
		  echo -e " "
		  echo -e "	$(basename "$0") -u"
		  echo -e "OR"
		  echo -e "	$(basename "$0") -unlock"
		  echo -e " "
		  echo -e "This will remove the lock for $(basename "$0")"
		  exit 
		fi
		touch "$LOCK"
		trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
		echo -e "======================================================================"
		echo -e "| - - - - - - - > [ S T A R T I N G    B A C K U P ] < - - - - - - - |"
		echo -e "======================================================================"
		echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date)"
		echo -e "$YELLOW""System:""$ENDCOLOR" "$(cat /etc/issue.net) $(uname -o) $(uname -r)"
		echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
		if [[ "$DESTINATION" ]] ; then
		  echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
		else
		  echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$BACKUP_DIR"
		fi
		echo -e "----------------------------------------------------------------------"
		restic backup "$BACKUP_DIR" --tag "$TAG" --verbose --exclude-caches --exclude-file="$EXCLUDES"
		echo -e "----------------------------------------------------------------------"
		echo -e "$YELLOW""End:""$ENDCOLOR" "$(date)"
		HRS=$((SECONDS / 3600))
		MIN=$(((SECONDS / 60) % 60))
		SEC=$((SECONDS % 60))
		if [[ "$HRS" -gt "0" ]] ; then
		  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$HRS hours $MIN minues $SEC seconds"
		elif [[ "$MIN" -gt "0" ]] ; then
		  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$MIN minutes $SEC seconds"
		else
		  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$SEC seconds"
		fi
		echo -e "======================================================================"
		echo -e "| - - - - - - - - > [ B A C K U P      E N D E D ] < - - - - - - - - |"
		echo -e "======================================================================"
	        ;;
	c|cleanup)
		if [ -e "$LOCK" ]; then
		  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
		  echo -e "If you are sure $(basename "$0") is not running, type"
		  echo -e " "
		  echo -e "	$(basename "$0") -u"
		  echo -e "OR"
		  echo -e "	$(basename "$0") -unlock"
		  echo -e " "
		  echo -e "This will remove the lock for $(basename "$0")"
		  exit 
		fi
		touch "$LOCK"
		trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
		if [[ "$KEEP_LAST" -gt "0" || "$KEEP_HOURLY" -gt "0" || "$KEEP_DAILY" -gt "0" || "$KEEP_WEEKLY" -gt "0" || "$KEEP_MONTHLY" -gt "0" || "$KEEP_YEARLY" -gt "0" ]] ; then
			echo -e "======================================================================"
	  		echo -e "|- - - - - - - > [ S T A R T I N G    C L E A N U P ] < - - - - - - -|"
			echo -e "======================================================================"
			echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date)"
			echo -e "$YELLOW""System:""$ENDCOLOR" "$(cat /etc/issue.net) $(uname -o) $(uname -r)"
			echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
			if [[ "$DESTINATION" ]] ; then
			  echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
			else
			  echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$BACKUP_DIR"
			fi
			echo -e "----------------------------------------------------------------------"
		        restic forget --keep-last $KEEP_LAST --keep-hourly $KEEP_HOURLY --keep-daily $KEEP_DAILY --keep-weekly $KEEP_WEEKLY --keep-monthly $KEEP_MONTHLY --keep-yearly $KEEP_YEARLY
		        restic prune --cleanup-cache
			if [[ -f "$DATEFILE" || "$CLEAN" -gt "0" ]] ; then
			  NOW=$(date +"%s")
			  NEXT=$(date -f "$DATEFILE" "+%s")
			  RESULT=$((NEXT-NOW))
			  DAYS=$((RESULT / 86400))
			  HOURS=$(((RESULT / 3600) % 24))
			  MINUTES=$(((RESULT / 60) % 60))
			  if [[ "$DAYS" -gt "0" ]] ; then
			    echo -e "$YELLOW""[Next check and cleanup in $DAYS days $HOURS hours and $MINUTES minutes...]""$ENDCOLOR"
			  elif [[ "$HOURS" -gt "0" ]] ; then
			    echo -e "$YELLOW""[Next check and cleanup in $HOURS hours and $MINUTES minutes...]""$ENDCOLOR"
			  elif [[ "$MINUTES" -gt "0" ]] ; then
			    echo -e "$YELLOW""[Next check and cleanup in $MINUTES minutes...]""$ENDCOLOR"
			  else
			    echo -e "$YELLOW""[Repo will be checked and cleaned in the next run...]""$ENDCOLOR"
			  fi
			fi
			echo -e "----------------------------------------------------------------------"
			echo -e "$YELLOW""End:""$ENDCOLOR" "$(date)"
			HRS=$((SECONDS / 3600))
			MIN=$(((SECONDS / 60) % 60))
			SEC=$((SECONDS % 60))
			if [[ "$HRS" -gt "0" ]] ; then
			  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$HRS hours $MIN minues $SEC seconds"
			elif [[ "$MIN" -gt "0" ]] ; then
			  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$MIN minutes $SEC seconds"
			else
			  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$SEC seconds"
			fi
			echo -e "======================================================================"
			echo -e "| - - - - - - - - > [ C L E A N U P    E N D E D ] < - - - - - - - - |"
			echo -e "======================================================================"
		else
			echo -e "$YELLOW""You have not indicated any policy value...""$ENDCOLOR"
			echo "If you want to use -c, -cleanup option you need to set the [KEEP] variables."
			echo "For more information about the Usage check out the following link:"
			echo "https://gitlab.com/sulfuror/rescript.sh/blob/master/README.md#usage"
		fi
		;;
	d|deep-check)
		if [ -e "$LOCK" ]; then
		  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
		  echo -e "If you are sure $(basename "$0") is not running, type"
		  echo -e " "
		  echo -e "	$(basename "$0") -u"
		  echo -e "OR"
		  echo -e "	$(basename "$0") -unlock"
		  echo -e " "
		  echo -e "This will remove the lock for $(basename "$0")"
		  exit 
		fi
		touch "$LOCK"
		trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
		restic check --read-data
		;;
	e)
		if [ -e "$LOCK" ]; then
		  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
		  echo -e "If you are sure $(basename "$0") is not running, type"
		  echo -e " "
		  echo -e "	$(basename "$0") -u"
		  echo -e "OR"
		  echo -e "	$(basename "$0") -unlock"
		  echo -e " "
		  echo -e "This will remove the lock for $(basename "$0")"
		  exit 
		fi
		touch "$LOCK"
		trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
		while [[ "$OPTARG" == "--help" ]] ; do
		  echo "[-e] is for the [exclusion] restic list"
		  echo "Usage:"
		  echo "  rescript -e [option]"
		  echo "OR"
		  echo "  rescript -e [--flag] [option]"
		  echo "Available options:"
		  echo "  --build		this flag requires one option [home|sys]"
		  echo "			to build an exclusion list based on common"
		  echo "			exclusions patterns, files and directories"
		  echo "	home		this will build a generic exclusion list"
		  echo "			for your [home] directory"
		  echo "	sys		this will build a generic exclusion list"
		  echo "			for your [system] directories"
		  echo "  --help		help for [-e]"
		  echo "  edit			this will open your exclusion file"
		  echo "			for you to add, remove or edit your"
		  echo "			exclusion list"
		  echo "  list			list exclusions"
		  echo ""
		  echo "WARNING: the [--build home] and [--build sys] options will override"
		  echo "any existing list in your rescript/config directory; if you already have"
		  echo "an exclusion list in this directory make a backup before using this two options"
		exit
		done
		while [[ "$OPTARG" == "--build" ]] ; do
		  if [[ -z "$3" ]] ; then
			echo "No [$OPTARG] indicated; use [-e --help] for usage."
		  elif [[ "$3" == "home" ]] ; then
			echo "# These are the default rescript exclusions for your home directory:" > "$EXCLUDES"
		  	echo "$HOME/.cache/*" >> "$EXCLUDES"
		  	echo "$HOME/.local/share/Trash/*" >> "$EXCLUDES"
		  	echo "$HOME/.rescript/lock/*" >> "$EXCLUDES"
		  	echo "$HOME/.gvfs" >> "$EXCLUDES"
		  	echo "$HOME/.dbus" >> "$EXCLUDES"
		  	echo "$HOME/.local/share/gvfs-metadata" >> "$EXCLUDES"
		  	echo "$HOME/.Private" >> "$EXCLUDES"
		  	echo "$HOME/.Trash" >> "$EXCLUDES"
		  	echo "$HOME/.cddb" >> "$EXCLUDES"
		  	echo "$HOME/.aptitude" >> "$EXCLUDES"
		  	echo "$HOME/.adobe" >> "$EXCLUDES"
		  	echo "$HOME/.bash_history" >> "$EXCLUDES"
		  	echo "$HOME/.dropbox" >> "$EXCLUDES"
		  	echo "$HOME/.dropbox-dist" >> "$EXCLUDES"
		  	echo "$HOME/.macromedia" >> "$EXCLUDES"
		  	echo "$HOME/.xsession-errors" >> "$EXCLUDES"
		  	echo "$HOME/.recently-used" >> "$EXCLUDES"
		  	echo "$HOME/.recently-used.xbel" >> "$EXCLUDES"
		  	echo "$HOME/.local/share/recently-used*" >> "$EXCLUDES"
		  	echo "$HOME/.thumbnails/*" >> "$EXCLUDES"
		  	echo "$HOME/.Xauthority" >> "$EXCLUDES"
		  	echo "$HOME/.ICEauthority" >> "$EXCLUDES"
		  	echo "$HOME/.gksu.lock" >> "$EXCLUDES"
		  	echo "$HOME/.pulse" >> "$EXCLUDES"
		  	echo "$HOME/.pulse-cookie" >> "$EXCLUDES"
		  	echo "$HOME/.esd_auth" >> "$EXCLUDES"
		  	echo "$HOME/.ecryptfs" >> "$EXCLUDES"
		  	echo "$HOME/.mozilla" >> "$EXCLUDES"
		  	echo "$HOME/.config/google-chrome" >> "$EXCLUDES"
		  	echo "$HOME/.config/chromium" >> "$EXCLUDES"
		  	echo "$HOME/.opera" >> "$EXCLUDES"
		  	echo "$HOME/.npm" >> "$EXCLUDES"
		  	echo "$HOME/.gnupg/rnd" >> "$EXCLUDES"
		  	echo "$HOME/.gnupg/random_seed" >> "$EXCLUDES"
		  	echo "$HOME/.gnupg/.#*" >> "$EXCLUDES"
		  	echo "$HOME/.gnupg/*.lock" >> "$EXCLUDES"
		  	echo "$HOME/.gnupg/gpg-agent-info-*" >> "$EXCLUDES"
			echo "$HOME/.config/**/Cache" >> "$EXCLUDES"
			echo "$HOME/.config/**/GPUCache" >> "$EXCLUDES"
			echo "$HOME/.config/**/ShaderCache" >> "$EXCLUDES"
			echo "$HOME/snap/**/.config/**/Cache" >> "$EXCLUDES"
			echo "$HOME/snap/**/.config/**/GPUCache" >> "$EXCLUDES"
			echo "$HOME/snap/**/.config/**/ShaderCache" >> "$EXCLUDES"
		  	echo "$HOME/Downloads" >> "$EXCLUDES"
		  	echo "*.lock" >> "$EXCLUDES"
		  	echo "*.bak" >> "$EXCLUDES"
		  	echo "*.backup" >> "$EXCLUDES"
		  	echo "*.backup*" >> "$EXCLUDES"
		  	echo "*~" >> "$EXCLUDES"
		  	echo "" >> "$EXCLUDES"
		  	echo "# Write your custom exclusions below:" >> "$EXCLUDES"
			echo "Done biulding home exclusion list; type [-e edit] to edit your list or [-e list] to view exclusions added."
		  elif [[ "$3" == "sys" ]] ; then
			echo "# These are the default rescript exclusions for your system:" > "$EXCLUDES"
			echo "/home/*" >> "$EXCLUDES"
			echo "/proc/*" >> "$EXCLUDES"
			echo "/sys/*" >> "$EXCLUDES"
			echo "/dev/*" >> "$EXCLUDES"
			echo "/run/*" >> "$EXCLUDES"
			echo "/mnt/*" >> "$EXCLUDES"
			echo "/media/*" >> "$EXCLUDES"
			echo "/etc/mtab" >> "$EXCLUDES"
			echo "/var/cache/apt/archives/*.deb" >> "$EXCLUDES"
			echo "lost+found/*" >> "$EXCLUDES"
			echo "/tmp/*" >> "$EXCLUDES"
			echo "/var/tmp/*" >> "$EXCLUDES"
			echo "/var/backups/*" >> "$EXCLUDES"
			echo "" >> "$EXCLUDES"
			echo "# Write your custom exclusions below:" >> "$EXCLUDES"
			echo "Done biulding system exclusion list; type [-e edit] to edit your list or [-e list] to view exclusions added."
		  fi
		exit
		done
		while [[ "$OPTARG" == "edit" ]] ; do
		  nano "$EXCLUDES"
		exit
		done
		while [[ "$OPTARG" == "list" ]] ; do
		  egrep -v '(^#|^\s*$|^\s*\t*#)' "$EXCLUDES"
		exit
		done
		;;
	h|help)
		echo "$Usage"
      		;;
	m|mount)
		if [ -e "$LOCK" ]; then
		  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
		  echo -e "If you are sure $(basename "$0") is not running, type"
		  echo -e " "
		  echo -e "	$(basename "$0") -u"
		  echo -e "OR"
		  echo -e "	$(basename "$0") -unlock"
		  echo -e " "
		  echo -e "This will remove the lock for $(basename "$0")"
		  exit 
		fi
		touch "$LOCK"
		trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
		rmount="$HOME/$(basename "$0")-$(date +%s)"
		mkdir "$rmount"
		restic mount "$rmount"
		rm -rf "$rmount"
		;;
	n|next-cleanup)
		if [[ -z "$CLEAN" || "$CLEAN" -lt "1" ]] ; then
		  echo -e "$YELLOW""You have not indicated any policy for the CLEAN value...""$ENDCOLOR"
		  echo "The scrip will run check, forget and prune every time it runs"
		  echo "unless you change the CLEAN variable at the beginning of this script."
		  echo "The number indicated in the CLEAN variable must be in days."
		  echo "For more information about the usage check out the following link:"
		  echo "https://gitlab.com/sulfuror/rescript.sh/blob/master/README.md#usage"
		else
		NOW=$(date +"%s")
		NEXT=$(date -f "$DATEFILE" "+%s")
		RESULT=$((NEXT-NOW))
		DAYS=$((RESULT / 86400))
		HOURS=$(((RESULT / 3600) % 24))
		MINUTES=$(((RESULT / 60) % 60))
		  if [[ "$DAYS" -gt "0" ]] ; then
		    echo -e "$YELLOW""Next check and cleanup in $DAYS days $HOURS hours and $MINUTES minutes...""$ENDCOLOR"
		  elif [[ "$HOURS" -gt "0" ]] ; then
		    echo -e "$YELLOW""Next check and cleanup in $HOURS hours and $MINUTES minutes...""$ENDCOLOR"
		  elif [[ "$MINUTES" -gt "0" ]] ; then
		    echo -e "$YELLOW""Next check and cleanup in $MINUTES minutes...""$ENDCOLOR"
		  else
		    echo -e "$YELLOW""Repo will be checked and cleaned in the next run...""$ENDCOLOR"
		  fi
		fi
		;;
	r)
		if [ -e "$LOCK" ]; then
		  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
		  echo -e "If you are sure $(basename "$0") is not running, type"
		  echo -e " "
		  echo -e "	$(basename "$0") -u"
		  echo -e "OR"
		  echo -e "	$(basename "$0") -unlock"
		  echo -e " "
		  echo -e "This will remove the lock for $(basename "$0")"
		  exit 
		fi
		touch "$LOCK"
		trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
		while [[ "$OPTARG" == "--help" ]] ; do
		  echo "[-r] is for [restore] command in restic"
		  echo "Usage:"
		  echo "  rescript -r [snapshot-ID]"
		  echo "Usage with flags:"
		  echo "  rescript -r [flag] [host|path|tag]"
		  echo "Available flags:"
		  echo "  --help		help for -r"
		  echo "  --host		only consider snapshots for this host"
		  echo "			when snapshot-ID is [latest]"
		  echo "  --path		only consider snapshots which include"
		  echo "			this [absolute] path for snapshot-ID [latest]"
		  echo "  --tag			only consider snapshots which include this"
		  echo "			taglist for snapshot-ID [latest]"
		exit
		done
		while [[ "$OPTARG" == "--host" || "$OPTARG" == "--tag" || "$OPTARG" == "--path" ]] ; do
		  if [[ -z "$3" ]] ; then
		    echo "No [$OPTARG] indicated; use [-r --help] for usage."
		  else
		    echo -e "======================================================================"
		    echo -e "|- - - - - - - > [ S T A R T I N G    R E S T O R E ] < - - - - - - -|"
		    echo -e "======================================================================"
		    echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date)"
		    echo -e "$YELLOW""System:""$ENDCOLOR" "$(cat /etc/issue.net) $(uname -o) $(uname -r)"
		    echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
		    if [[ "$DESTINATION" ]] ; then
		      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
		    else
		      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$BACKUP_DIR"
		    fi
		    echo -e "----------------------------------------------------------------------"
		    if [[ "$DESTINATION" ]] ; then
		      echo -e "$YELLOW""Restoring latest snapshot [$OPTARG: $3] from:""$ENDCOLOR" "$DESTINATION..."
		    else
		      echo -e "$YELLOW""Restoring latest snapshot [$OPTARG: $3] from:""$ENDCOLOR" "$BACKUP_DIR"
		    fi
		    if [[ "$OPTARG" == "--path" ]] ; then
		      restic_restore="$HOME/restore-latest-by-path-$(date +%s)"
		    else
		      restic_restore="$HOME/restore-latest-$3-$(date +%s)"
		    fi
		    restic restore --verify "$OPTARG" "$3" latest --target "$restic_restore"
		    echo -e "----------------------------------------------------------------------"
		    echo -e "$YELLOW""End:""$ENDCOLOR" "$(date)"
		    HRS=$((SECONDS / 3600))
		    MIN=$(((SECONDS / 60) % 60))
		    SEC=$((SECONDS % 60))
		    if [[ "$HRS" -gt "0" ]] ; then
		      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$HRS hours $MIN minues $SEC seconds"
		    elif [[ "$MIN" -gt "0" ]] ; then
		      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$MIN minutes $SEC seconds"
		    else
		      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$SEC seconds"
		    fi
		    echo -e "======================================================================"
		    echo -e "| - - - - - - > [ R E S T O R E    C O M P L E T E D ] < - - - - - - |"
		    echo -e "======================================================================"
		  fi
		exit
		done
		while [[ "$OPTARG" ]] ; do
		  echo -e "======================================================================"
		  echo -e "|- - - - - - - > [ S T A R T I N G    R E S T O R E ] < - - - - - - -|"
		  echo -e "======================================================================"
		  echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date)"
		  echo -e "$YELLOW""System:""$ENDCOLOR" "$(cat /etc/issue.net) $(uname -o) $(uname -r)"
		  echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
		  if [[ "$DESTINATION" ]] ; then
		    echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
		  else
		    echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$BACKUP_DIR"
		  fi
		  echo -e "----------------------------------------------------------------------"
		  if [[ "$DESTINATION" ]] ; then
		    if [[ "$3" ]] ; then
		      echo -e "$YELLOW""Restoring latest snapshot [$OPTARG: $3] from:""$ENDCOLOR" "$DESTINATION..."
		    else
		      echo -e "$YELLOW""Restoring $OPTARG snapshot from:""$ENDCOLOR" "$DESTINATION..."
		    fi
		  else
		    if [[ "$3" ]] ; then
		      echo -e "$YELLOW""Restoring latest snapshot [$OPTARG: $3] from:""$ENDCOLOR" "$BACKUP_DIR"
		    else
		      echo -e "$YELLOW""Restoring $OPTARG snapshot from:""$ENDCOLOR" "$BACKUP_DIR"
		    fi
		  fi
		  restic_restore="$HOME/restore-$OPTARG-$(date +%s)"
		  restic restore --verify "$OPTARG" --target "$restic_restore"
		  echo -e "----------------------------------------------------------------------"
		  echo -e "$YELLOW""End:""$ENDCOLOR" "$(date)"
		  HRS=$((SECONDS / 3600))
		  MIN=$(((SECONDS / 60) % 60))
		  SEC=$((SECONDS % 60))
		  if [[ "$HRS" -gt "0" ]] ; then
		    echo -e "$YELLOW""Duration:""$ENDCOLOR" "$HRS hours $MIN minues $SEC seconds"
		  elif [[ "$MIN" -gt "0" ]] ; then
		    echo -e "$YELLOW""Duration:""$ENDCOLOR" "$MIN minutes $SEC seconds"
		  else
		    echo -e "$YELLOW""Duration:""$ENDCOLOR" "$SEC seconds"
		  fi
		  echo -e "======================================================================"
		  echo -e "| - - - - - - > [ R E S T O R E    C O M P L E T E D ] < - - - - - - |"
		  echo -e "======================================================================"
		exit
		done
		;;
	v|version)
	        echo "$Version"
        	;;
	u|unlock)
		if [[ ! -e "$LOCK" ]]; then
			echo -e "$YELLOW""No locks found...""$ENDCOLOR"
		   else
			rm -rf "$LOCK"
			echo -e "$YELLOW""Script unlocked...""$ENDCOLOR"
		fi
		;;
	\?)
	        echo "Unknown option [-$OPTARG]; use [-h] or [help] for available commands and options"
	        ;;
	:)
		echo "You have not indicated any option for [-$OPTARG]"
		echo "	-e requires an option to edit / build your exclusion list"
		echo "	   [use -e --help for usage and available options]"
		echo "	-r requires a snapshot-ID to restore [use -r --help for"
		echo "	   usage and available flags]"
	        ;;
	*)
	        echo "Unknown error while processing options"
		echo "$Usage"
	        ;;
      esac
    exit
  done
shift $((OPTIND - 1))

# Commands
if [[ -n "$1" ]] ; then
  if [[ "$1" == "help" ]] ; then
    if [ -e "$LOCK" ]; then
	echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
	echo -e "If you are sure $(basename "$0") is not running, type"
	echo -e " "
	echo -e "	$(basename "$0") -u"
	echo -e "OR"
	echo -e "	$(basename "$0") -unlock"
	echo -e " "
	echo -e "This will remove the lock for $(basename "$0")"
        exit
    fi
    touch "$LOCK"
    trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
    echo "$Usage"
    exit
  elif [[ "$1" == "version" ]] ; then
    if [ -e "$LOCK" ]; then
	echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
	echo -e "If you are sure $(basename "$0") is not running, type"
	echo -e " "
	echo -e "	$(basename "$0") -u"
	echo -e "OR"
	echo -e "	$(basename "$0") -unlock"
	echo -e " "
	echo -e "This will remove the lock for $(basename "$0")"
        exit
    fi
    touch "$LOCK"
    trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
    echo "$Version"
    exit
  elif [[ "$1" == "backup" ]] ; then
    if [ -e "$LOCK" ]; then
      echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
      echo -e "If you are sure $(basename "$0") is not running, type"
      echo -e " "
      echo -e "		$(basename "$0") -u"
      echo -e "OR"
      echo -e "		$(basename "$0") -unlock"
      echo -e " "
      echo -e "This will remove the lock for $(basename "$0")"
      exit 
    fi
    touch "$LOCK"
    trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
    echo -e "======================================================================"
    echo -e "| - - - - - - - > [ S T A R T I N G    B A C K U P ] < - - - - - - - |"
    echo -e "======================================================================"
    echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date)"
    echo -e "$YELLOW""System:""$ENDCOLOR" "$(cat /etc/issue.net) $(uname -o) $(uname -r)"
    echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
    if [[ "$DESTINATION" ]] ; then
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
    else
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$BACKUP_DIR"
    fi
    echo -e "----------------------------------------------------------------------"
    restic backup "$BACKUP_DIR" --tag "$TAG" --verbose --exclude-caches --exclude-file="$EXCLUDES"
    echo -e "----------------------------------------------------------------------"
    echo -e "$YELLOW""End:""$ENDCOLOR" "$(date)"
    HRS=$((SECONDS / 3600))
    MIN=$(((SECONDS / 60) % 60))
    SEC=$((SECONDS % 60))
    if [[ "$HRS" -gt "0" ]] ; then
      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$HRS hours $MIN minues $SEC seconds"
    elif [[ "$MIN" -gt "0" ]] ; then
      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$MIN minutes $SEC seconds"
    else
      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$SEC seconds"
    fi
    echo -e "======================================================================"
    echo -e "| - - - - - - - - > [ B A C K U P      E N D E D ] < - - - - - - - - |"
    echo -e "======================================================================"
    exit
  else
    if [ -e "$LOCK" ]; then
	echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
	echo -e "If you are sure $(basename "$0") is not running, type"
	echo -e " "
	echo -e "	$(basename "$0") -u"
	echo -e "OR"
	echo -e "	$(basename "$0") -unlock"
	echo -e " "
	echo -e "This will remove the lock for $(basename "$0")"
        exit
    fi
    touch "$LOCK"
    trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
    restic "$@"
    exit
  fi
fi

# Bail if script is already running
if [ -e "$LOCK" ]; then
  echo -e "$YELLOW""WARNING:""$ENDCOLOR" "$(basename "$0") is already running..."
  echo -e "If you are sure $(basename "$0") is not running, type"
  echo -e " "
  echo -e "	$(basename "$0") -u"
  echo -e "OR"
  echo -e "	$(basename "$0") -unlock"
  echo -e " "
  echo -e "This will remove the lock for $(basename "$0")"
  exit 
fi

touch "$LOCK"
trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
# ------------------------------------------------------------------------------- #

echo -e "======================================================================"
echo -e "| - - - - - - - > [ S T A R T I N G    B A C K U P ] < - - - - - - - |"
echo -e "======================================================================"
echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date)"
echo -e "$YELLOW""System:""$ENDCOLOR" "$(cat /etc/issue.net) $(uname -o) $(uname -r)"
echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
if [[ "$DESTINATION" ]] ; then
  echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
else
  echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$BACKUP_DIR"
fi
echo -e "----------------------------------------------------------------------"

# Backup and exclusions
echo -e "$YELLOW""[Taking a Snapshot...]""$ENDCOLOR"
restic backup "$BACKUP_DIR" --tag "$TAG" --verbose --exclude-caches --exclude-file="$EXCLUDES"

EXCLUSIONS=$(egrep -v -n -c '(^#|^\s*$|^\s*\t*#)' "$EXCLUDES")
echo -e "$YELLOW""There are "$EXCLUSIONS" exclusion rules...""$ENDCOLOR"

echo -e "----------------------------------------------------------------------"
# Snapshot List
echo -e "$YELLOW""[Snapshots List...]""$ENDCOLOR"
restic snapshots

# Check and Clean Repo Based on User's Policy
if [[ -f "$DATEFILE" || "$CLEAN" -gt "0" ]]; then
  NOW=$(date +"%s")
  NEXT=$(date -f "$DATEFILE" "+%s")
  RESULT=$((NEXT-NOW))
  DAYS=$((RESULT / 86400))
  HOURS=$(((RESULT / 3600) % 24))
  MINUTES=$(((RESULT / 60) % 60))
  if [[ "$NOW" -lt "$NEXT" ]] ; then
    if [[ "$DAYS" -gt "0" ]] ; then
      echo -e "$YELLOW""[Next check and cleanup in $DAYS days $HOURS hours and $MINUTES minutes...]""$ENDCOLOR"
    elif [[ "$HOURS" -gt "0" ]] ; then
      echo -e "$YELLOW""[Next check and cleanup in $HOURS hours and $MINUTES minutes...]""$ENDCOLOR"
    elif [[ "$MINUTES" -gt "0" ]] ; then
      echo -e "$YELLOW""[Next check and cleanup in $MINUTES minutes...]""$ENDCOLOR"
    else
      echo -e "$YELLOW""[Repo will be checked and cleaned in the next run...]""$ENDCOLOR"
    fi
  else 
    if [[ "$KEEP_LAST" -gt "0" || "$KEEP_HOURLY" -gt "0" || "$KEEP_DAILY" -gt "0" || "$KEEP_WEEKLY" -gt "0" || "$KEEP_MONTHLY" -gt "0" || "$KEEP_YEARLY" -gt "0" ]] ; then
      echo -e "$YELLOW""[Cleaning Repo...]""$ENDCOLOR"
      restic forget --keep-last $KEEP_LAST --keep-hourly $KEEP_HOURLY --keep-daily $KEEP_DAILY --keep-weekly $KEEP_WEEKLY --keep-monthly $KEEP_MONTHLY --keep-yearly $KEEP_YEARLY
      restic prune
      echo -e "$YELLOW""[Checking for Errors in Repo...]""$ENDCOLOR"
      restic check --cleanup-cache
      if [[ "$CLEAN" -gt "0" ]] ; then
        echo -e "$YELLOW""[Done Cleaning; Next Check and Cleanup Will Be Done in $CLEAN days...]""$ENDCOLOR"
        date -d now+"$CLEAN"days > "$DATEFILE"
      fi
    fi
  fi
else 
    if [[ "$KEEP_LAST" -gt "0" || "$KEEP_HOURLY" -gt "0" || "$KEEP_DAILY" -gt "0" || "$KEEP_WEEKLY" -gt "0" || "$KEEP_MONTHLY" -gt "0" || "$KEEP_YEARLY" -gt "0" ]] ; then
      echo -e "$YELLOW""[Cleaning Repo...]""$ENDCOLOR"
      restic forget --keep-last $KEEP_LAST --keep-hourly $KEEP_HOURLY --keep-daily $KEEP_DAILY --keep-weekly $KEEP_WEEKLY --keep-monthly $KEEP_MONTHLY --keep-yearly $KEEP_YEARLY
      restic prune
      echo -e "$YELLOW""[Checking for Errors in Repo...]""$ENDCOLOR"
      restic check --cleanup-cache
    fi
fi


# Stats
echo -e "----------------------------------------------------------------------"
echo -e "$YELLOW""[Latest Snapshots Size...]""$ENDCOLOR"
restic stats latest
echo -e "$YELLOW""[Deduplicated Size for Latest Snapshot...]""$ENDCOLOR"
restic stats --mode raw-data latest
echo -e "$YELLOW""[Original Files Size...]""$ENDCOLOR"
restic stats
echo -e "$YELLOW""[Deduplicated Size for All Snapshots...]""$ENDCOLOR"
restic stats --mode raw-data
# Time and Runtime
echo -e "----------------------------------------------------------------------"
echo -e "$YELLOW""End:""$ENDCOLOR" "$(date)"
HRS=$((SECONDS / 3600))
MIN=$(((SECONDS / 60) % 60))
SEC=$((SECONDS % 60))
if [[ "$HRS" -gt "0" ]] ; then
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$HRS hours $MIN minues $SEC seconds"
elif [[ "$MIN" -gt "0" ]] ; then
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$MIN minutes $SEC seconds"
else
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$SEC seconds"
fi
echo -e "======================================================================"
echo -e "| - - - - - - - - > [ B A C K U P      E N D E D ] < - - - - - - - - |"
echo -e "======================================================================"

# Reset credentials
export RESTIC_PASSWORD=""
export B2_ACCOUNT_ID=""
export B2_ACCOUNT_KEY=""

exit 0