#!/usr/bin/env bash
# ============================================================== #
version="3.8"
usage="
Author		: Sulfuror, Copyright (c) 2018 <sulfuror@gmail.com>
URL		: https://gitlab.com/sulfuror/rescript.sh
License		: BSD 2-clause 'Simplified' License
Version		: $version
Description	: rescript is a bash script created to manage
		  backups made with restic program.

'restic is a backup program which allows saving multiple revisions 
of files and directories in an encrypted repository 
stored on different backends.'

For more information about restic visit https://restic.net

This script will run backup, snapshots, forget, prune, check and
stats commands automatically by just indicating the name given
to your repository. e.g.:

  rescript [repo_name]

All restic commands are available within this script except for
[backup], which exists but it will use your configuration
file to perform a backup.

Usage:
  rescript [config_command]
OR
  rescript [repo_name] [rescript_command]
OR
  rescript [repo_name] [restic_command]
  
Rescript configuration commands:
  config		Rescript configuration; set your default
  			text editor, open, delete or modify your
  			configuration and exclusion files. This command
  			does not need a [repo_name].
  editor		Change the default rescript text editor used
  			to open your configuration and exclusions files.
  			This command does not need a [repo_name].
  help			Display rescript help and usage. This command
  			does not need a [repo_name].
  install		Install rescript (this just move the script
  			to your .local/bin directory for convenience.
  			This command does not need a [repo_name].
  update		Update is used to update the script itself
  			when a new version is available.
  
Rescript commands:
  backup		Take a snapshot using the values set in
  			your configuration file.
  checkout		This command will execute check using
  			[--read-data-subset] and selecting a random
  			number between 1-10 out of 10 groups.
  cleanup		Forget and prune according to the policies
  			in your configuration file.
  logs			This command needs a flag to view, list
			or delete your log files.
  mounter		Mount a restic repo.
  restorer		Restore a restic snapshot.	
  unlocker		Remove lock created by rescript.
  version		Display rescript version. This command does
  			not need a [repo_name].

Rescript glogal flags:
  -h, --help		This flag is available for all rescript commands
  			and it can be used to display the usage for every
  			single rescript command.
  -l, --log		This flag is available for all rescript and restic
  			commands. This will create a log file
  			with the command output. You can combine this
  			flag with [--time].
  -t, --time		This flag is available ONLY for restic commands.
			This flag will display an output with the date,
			time and duration of the command. You can
			combine this flag with [--log].

These global flags must be used BEFORE the command. To see usage and
flags available for a specific command type:
  rescript help [command]
"
# ============================================================== #
YELLOW="\033[33m"
ENDCOLOR="\033[0m"
SECONDS=0
EXCLUDES="$HOME/.rescript/config/$1-exclusions"
LOCK="$HOME/.rescript/lock/$1.lock"
RMOUNT="$HOME/"$1"-repo-$(date +%s)"
REPO="$1"

# Create a rescript directories if they are not present
if [[ ! -d "$HOME/.rescript" ]]; then
  mkdir -p "$HOME/.rescript"
fi
if [[ ! -d "$HOME/.rescript/config" ]]; then
  mkdir -p "$HOME/.rescript/config"
fi
if [[ ! -d "$HOME/.rescript/lock" ]]; then
  mkdir -p "$HOME/.rescript/lock"
fi
if [[ ! -d "$HOME/.rescript/logs" ]]; then
  mkdir -p "$HOME/.rescript/logs"
fi
# Create "editor" file if not present
if [[ ! -f "$HOME/.rescript/config/.editor" ]] ; then
  touch $HOME/.rescript/config/.editor
fi
EDITOR="$(cat $HOME/.rescript/config/.editor)"
# Set PATH so it includes user's private bin if it exists (cron jobs may require this)
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

function opsys {
  OS_NAME="$(uname -s)"
  if [[ "$OS_NAME" == "Linux" || "$OS_NAME" == "Linux" ]] ; then
    echo -e "$(lsb_release -ds)"
  elif [[ "$OS_NAME" == "FreeBSD"* ]] ; then
    echo -e "$(uname -rs)"
  elif [[ "$OS_NAME" == "Darwin"* ]] ; then
    OS="$(sw_vers -productName)"
    OS_VERS="$(sw_vers -productVersion)"
    echo -e "$OS $OS_VERS"
  fi
}

function duration {
  D="$((SECONDS/60/60/24))"
  H="$((SECONDS/60/60%24))"
  M="$((SECONDS/60%60))"
  S="$((SECONDS%60))"
  if [[ "$D" == "1" ]] ; then
    DAYS="day"
  else
    DAYS="days"
  fi
  if [[ "$H" == "1" ]] ; then
    HRS="hour"
  else
    HRS="hours"
  fi
  if [[ "$M" == "1" ]] ; then
    MIN="minute"
  else
    MIN="minutes"
  fi
  if [[ "$S" == "1" ]] ; then
    SEC="second"
  else
    SEC="seconds"
  fi
  if [[ "$D" -gt "0" ]] ; then
    echo "$D $DAYS $H $HRS $M $MIN and $S $SEC"
  elif [[ "$H" -gt "0" ]] ; then
    echo "$H $HRS $M $MIN and $S $SEC"
  elif [[ "$M" -gt "0" ]] ; then
    echo "$M $MIN and $S $SEC"
  else
    echo "$S $SEC"
  fi
}
# ============================================================== #
# Menu								 #
# ============================================================== #
# Select Editor Menu
function select_editor {
  clear
  echo "======================"
  echo "  Select Text Editor  "
  echo "======================"
  echo " [1] Nano             "
  echo " [2] Vim              "
  echo " [3] Gedit            "
  echo " [4] Mousepad         "
  echo " [5] Leafpad          "
  echo " [6] Pluma            "
  echo " [7] Kate             "
  echo " [8] Other            "
  echo " [9] Exit             "
  echo "======================"
  read -p "Select the Text Editor you want to use [ 1 - 9 ]: " texteditor
  if [[ "$texteditor" == "1" || "$texteditor" == "Nano" || "$texteditor" == "nano" ]] ; then
    echo "nano" > $HOME/.rescript/config/.editor
    echo "You have selected [Nano] as your default text editor."
  elif [[ "$texteditor" == "2" || "$texteditor" == "Vim" || "$texteditor" == "vim" ]] ; then
    echo "vim" > $HOME/.rescript/config/.editor
    echo "You have selected [Vim] as your default text editor."
  elif [[ "$texteditor" == "3" || "$texteditor" == "Gedit" || "$texteditor" == "gedit" ]] ; then
    echo "gedit" > $HOME/.rescript/config/.editor
    echo "You have selected [Gedit] as your default text editor."
  elif [[ "$texteditor" == "4" || "$texteditor" == "Mousepad" || "$texteditor" == "mousepad" ]] ; then
    echo "mousepad" > $HOME/.rescript/config/.editor
    echo "You have selected [Mousepad] as your default text editor."
  elif [[ "$texteditor" == "5" || "$texteditor" == "Leafpad" || "$texteditor" == "leafpad" ]] ; then
    echo "leafpad" > $HOME/.rescript/config/.editor
    echo "You have selected [Leafpad] as your default text editor."
  elif [[ "$texteditor" == "6" || "$texteditor" == "Pluma" || "$texteditor" == "pluma" ]] ; then
    echo "pluma" > $HOME/.rescript/config/.editor
    echo "You have selected [Pluma] as your default text editor."
  elif [[ "$texteditor" == "7" || "$texteditor" == "Kate" || "$texteditor" == "kate" ]] ; then
    echo "kate" > $HOME/.rescript/config/.editor
    echo "You have selected [Kate] as your default text editor."
  elif [[ "$texteditor" == "8" || "$texteditor" == "Other" || "$texteditor" == "other" ]] ; then
    read -p "Type the executable name of the Text Editor you want to use: " othertextedit
    echo "$othertextedit" > $HOME/.rescript/config/.editor
    echo "You have selected [$othertextedit] as your default text editor."
  elif [[ "$texteditor" == "9" || "$texteditor" == "Exit" || "$texteditor" == "exit" ]] ; then
    echo "Exiting..."
    exit
  else
    echo "Invalid option; exiting..."  
    exit
  fi
}

# Main menu
function main_menu {
  echo "======================"
  echo "        Menu          "
  echo "======================"
  echo " [1] Configuration    "
  echo " [2] Exclusions       "
  echo " [3] Exit             "
  echo "======================"
  read -p "Select an option and press Enter [ 1 - 3 ]: " main
  if [[ "$main" == "1" || "$main" == "Configuration" || "$main" == "configuration" ]] ; then
    clear
    config_menu
  elif [[ "$main" == "2" || "$main" == "Exclusions" || "$main" == "exclusions" ]] ; then
    clear
    exclusion_menu    
  elif [[ "$main" == "3" || "$main" == "Exit" || "$main" == "exit" ]] ; then
    echo "Exiting..."
    exit    
  else
    clear
    echo "No valid option..."
    main_menu
  fi
}

# Configuration menu
function config_menu {
  echo "======================"
  echo "       Options        "
  echo "======================"
  echo " [1] Edit Existing    "
  echo " [2] New Repository   "
  echo " [3] Delete Config    "
  echo " [4] Back to Main Menu"
  echo " [5] Exit             "
  echo "======================"
  read -p "Select an option and press Enter [ 1 - 5 ]: " cfgopt
  if [[ "$cfgopt" == "1" || "$cfgopt" == "Edit" || "$cfgopt" == "edit" ]] ; then
    clear
    edit_config_files
  elif [[ "$cfgopt" == "2" || "$cfgopt" == "New" || "$cfgopt" == "new" ]] ; then
    new_config_file
  elif [[ "$cfgopt" == "3" || "$cfgopt" == "Delete" || "$cfgopt" == "delete" ]] ; then
    clear
    delete_config_file
  elif [[ "$cfgopt" == "4" || "$cfgopt" == "Back" || "$cfgopt" == "back" ]] ; then
    clear
    main_menu
  elif [[ "$cfgopt" == "5" || "$cfgopt" == "Exit" || "$cfgopt" == "exit" ]] ; then
    echo "Exiting..."
    exit
  else
    clear
    echo "No valid selection; try again..."
    config_menu
  fi
}

function edit_config_files {
  echo "======================"
  echo "     Config Files     "
  echo "======================"
  echo " [1] Back to Main Menu"
  echo " [2] Exit             "
  echo "----------------------"
  ls $HOME/.rescript/config | grep -e '.conf' | sed -e 's/\.conf$//'
  echo "======================"
  read -p "Write the name of the repo file to open or one of the options above [ 1 - 2 ]: " conf
  if [[ "$conf" == "1" || "$conf" == "Back" || "$conf" == "back" ]] ; then
    clear
    config_menu
  elif [[ "$conf" == "2" || "$conf" == "Exit" || "$conf" == "exit" ]] ; then
    echo "Exiting..."
    exit
  elif [[ -e $HOME/.rescript/config/$conf.conf ]] ; then
    "$EDITOR" $HOME/.rescript/config/$conf.conf 2> /dev/null
    clear
    edit_config_files
  else
    clear
    echo "There is no repo called ["$conf"]; try again with the correct name."
    edit_config_files
  fi
}  

function new_config_file {
  new_repo="$HOME/.rescript/config/.new"
  touch "$new_repo"
  trap 'rm -rf "$new_repo"' INT QUIT TERM EXIT
  {
  echo "# =============================================================================== #"
  echo "#                   R E S C R I P T    C O N F I G U R A T I O N                  #"
  echo "# =============================================================================== #"
  echo "# You need to set your restic password (password for the repository), the"
  echo "# directory for your repository, the backup directory (by default the backup"
  echo "# directory is your Home directory), the destination name of your backup"
  echo "# (local, S3, B2, Wasabi, remote host, etc.), your tag (empty by default if used)"
  echo "# and your "keep" and "excludes" policies."
  echo "# ------------------------------------------------------------------------------- #"
  echo "#                              R E P O    I N F O                                 #"
  echo "# ------------------------------------------------------------------------------- #"
  echo "# Set restic password, repository location/directory and backup directory."
  echo 'RESTIC_PASSWORD=""'
  echo 'RESTIC_REPO=""'
  echo 'BACKUP_DIR="$HOME"'
  echo ""
  echo "# Keep Policies (leave blank if not used)"
  echo 'KEEP_LAST=""'
  echo 'KEEP_HOURLY="8"'
  echo 'KEEP_DAILY="7"'
  echo 'KEEP_WEEKLY="4"'
  echo 'KEEP_MONTHLY="12"'
  echo 'KEEP_YEARLY="10"'
  echo 'KEEP_WITHIN=""'
  echo 'KEEP_TAG=""'
  echo ""
  echo "# B2 Credentials (leave blank if not used)"
  echo 'B2_ID=""'
  echo 'B2_KEY=""'
  echo ""
  echo "# AWS Credentials (leave blank if not used)"
  echo 'AWS_ID=""'
  echo 'AWS_KEY=""'
  echo ""
  echo "# Optional values; The "DESTINATION" value is just use in this script to display"
  echo "# in the output the name of your destination (e.g.: Google Drive, Amazon, B2, Wasabi,"
  echo "# etc.). The "TAG" value will tag your snapshots with any name/tag you want."
  echo "# The "CLEAN" value determine when it will execute the forget, prune and check"
  echo "# commands; this value must be set in days and by default the number 7 means"
  echo "# it will do these tasks every seven (7) days. These values CAN be left blank"
  echo "# if you are not planning on use them."
  echo 'CLEAN="7"'
  echo 'TAG=""'
  echo 'DESTINATION=""'
  echo 'HOST=""'
  echo ""
  echo "# The variable "LOGGING" is "yes" by default. If you don't want logs to be saved"
  echo "# at .rescript/logs directory just change the "yes" to "no". This will only save"
  echo "# a log when the script is run; options and commands do not save logs."
  echo 'LOGGING="yes"'
  } > "$new_repo"
  chmod 700 "$new_repo"
  read -p "Write the name for your new repository (case sensitive): " repo_name
  if [[ $repo_name ]] ; then
    mv "$new_repo" $HOME/.rescript/config/$repo_name.conf
    touch $HOME/.rescript/config/$repo_name-exclusions
    touch $HOME/.rescript/config/$repo_name-datefile
    date -R > $HOME/.rescript/config/$repo_name-datefile
    {
     echo "# These are the default rescript exclusions:"
     echo "$HOME/.cache/*"
     echo "$HOME/.local/share/Trash/*"
     echo "$HOME/.rescript/lock/*"
     echo "$HOME/.Trash"
     echo "$HOME/.Private"
     echo "$HOME/.ecryptfs"
     echo ""
     echo "# Write your custom exclusions below:"
    } > $HOME/.rescript/config/$repo_name-exclusions
    date -R > $HOME/.rescript/config/$repo_name-datefile
    echo "["$repo_name"] config file have been created. If this is a new repository,"
    echo "you must run [rescript "$repo_name" init] to initialize your new repository"
    echo "before executing any other command. You also need to edit your new config"
    echo "file to proceed."
    read -p "Would you like to open ["$repo_name"] config file now? y/n " answer
    if [[ "$answer" == "y" || "$answer" == "yes" || "$answer" == "Yes" || "$answer" == "YES" || "$answer" == "Y" ]] ; then
      "$EDITOR" $HOME/.rescript/config/$repo_name.conf 2> /dev/null
      clear
      config_menu
    elif [[ "$answer" == "n" || "$answer" == "no" || "$answer" == "No" || "$answer" == "NO" || "$answer" == "N" ]] ; then
      echo "Remember to configure your repo file before continuing!"
      exit
    else
      clear
      echo "Invalid action..."
      config_menu
    fi
  else
    rm -rf "$new_repo"
    echo "Exiting..."
    exit
  fi
}

function delete_config_file {
  echo "======================"
  echo "     Config Files     "
  echo "======================"
  echo " [1] Back to Main Menu"
  echo " [2] Exit             "
  echo "----------------------"
  ls $HOME/.rescript/config | grep -e '.conf' | sed -e 's/\.conf$//'
  echo "======================"
  read -p "Type the name of the repo file you wish to delete or one of the optinos above [ 1 - 2 ]: " del
  if [[ "$del" == "1" || "$del" == "Back" ||"$del" == "back" ]] ; then
    clear
    config_menu
  elif [[ "$del" == "2" || "$del" == "Exit" ||"$del" == "exit" ]] ; then
    echo "Exiting..."
    exit
  elif [[ "$HOME/.rescript/config/$del.conf" ]] ; then
    read -p "Are you sure you want to delete ["$del"]? y/n: " ans
    if [[ "$ans" == "y" || "$ans" == "yes" || "$ans" == "Yes" || "$ans" == "YES" || "$ans" == "Y" ]] ; then
      rm -rf $HOME/.rescript/config/$del.conf
      rm -rf $HOME/.rescript/config/$del-exclusions
      rm -rf $HOME/.rescript/config/$del-datefile
      clear
      echo "[$del] repository configuration have been removed."
      delete_config_file
    elif [[ "$ans" == "n" || "$ans" == "no" || "$ans" == "No" || "$ans" == "NO" || "$ans" == "N" ]] ; then
      clear
      delete_config_file
    elif [[ "$ans" == "exit" || "$ans" == "Exit" ]] ; then
      echo "Exiting..."
      exit
    else
      echo "No action indicated; exiting..."
      exit
    fi
  else
    clear
    echo "No action indicated..."
    exit
  fi
}

# Exclusions menu
function exclusion_menu {
  echo "======================"
  echo "  Exclusions Options  "
  echo "======================"
  echo " [1] Edit Existing    "
  echo " [2] Build Exclusions "
  echo " [3] Back to Main Menu"
  echo " [4] Exit             "
  echo "======================"
  read -p "Select an option and press Enter [ 1 - 4 ]: " excl_opt
  if [[ "$excl_opt" == "1" || "$excl_opt" == "Edit" ||"$excl_opt" == "edit" ]] ; then
    clear
    edit_exclusions
  elif [[ "$excl_opt" == "2" || "$excl_opt" == "Build" ||"$excl_opt" == "build" ]] ; then
    clear
    build_exclusions
  elif [[ "$excl_opt" == "3" || "$excl_opt" == "Back" ||"$excl_opt" == "back" ]] ; then
    clear
    main_menu
  elif [[ "$excl_opt" == "4" || "$excl_opt" == "Exit" ||"$excl_opt" == "exit" ]] ; then
    echo "Exiting..."
    exit
  else
    clear
    echo "No valid action indicated..."
    exclusion_menu
  fi
}

function edit_exclusions {
  echo "======================"
  echo "   Exclusion Files    "
  echo "======================"
  echo " [1] Back             "
  echo " [2] Exit             "
  echo "----------------------"
  ls $HOME/.rescript/config | grep -e '-exclusions' | sed -e 's/\-exclusions$//'
  echo "======================"
  read -p "Type the name of the exclusions file you wish to open or one of the options above [ 1 - 2 ]: " excl_edit
  if [[ "$excl_edit" == "1" || "$excl_edit" == "Back" ||"$excl_edit" == "back" ]] ; then
    clear
    exclusion_menu
  elif [[ "$excl_edit" == "2" || "$excl_edit" == "Exit" ||"$excl_edit" == "exit" ]] ; then
    echo "Exiting..."
    exit
  elif [[ -e "$HOME/.rescript/config/$excl_edit-exclusions" ]] ; then
    "$EDITOR" "$HOME/.rescript/config/$excl_edit-exclusions" 2> /dev/null
    clear
    edit_exclusions
  else
    clear
    echo "There is no exclusion file called ["$excl_edit"]; try again with the correct name."
    edit_exclusions
  fi  
}

function build_exclusions {
  echo "======================"
  echo "    Build Options     "
  echo "======================"
  echo " [1] For Home Dir     "
  echo " [2] For System Dir   "
  echo " [3] Back             "
  echo " [4] Exit             "
  echo "======================"
  read -p "Select an option and press Enter [ 1 - 4 ]: " excl_bld
  if [[ "$excl_bld" == "1" || "$excl_bld" == "Home" ||"$excl_bld" == "home" ]] ; then
    clear
    echo "======================"
    echo " Exclusion Files List "
    echo "======================"
    echo " [1] Back             "
    echo " [2] Exit             "
    echo "----------------------"    
    ls $HOME/.rescript/config | grep -e '-exclusions' | sed -e 's/\-exclusions$//'
    echo "======================"
    read -p "Type the name of the exclusion file you want to build or one of the options above [ 1 - 2 ]: " excl_file
    if [[ "$excl_file" == "1" || "$excl_file" == "Back" || "$excl_file" == "back" ]] ; then
      clear
      build_exclusions
    elif [[ "$excl_file" == "2" || "$excl_file" == "Exit" || "$excl_file" == "exit" ]] ; then
      echo "Exiting..."
      exit
    elif [[ -e "$HOME/.rescript/config/$excl_file-exclusions" ]] ; then 
      echo "This action will override your existing [$excl_file] exclusion file."
      read -p "Are you sure you want to proceed? y/n: " ans_excl
      if [[ "$ans_excl" == "yes" || "$ans_excl" == "y" || "$ans_excl" == "Yes" || "$ans_excl" == "Y" || "$ans_excl" == "YES" ]] ; then
        if [[ "$excl_file" == "1" || "$excl_file" == "Back" || "$excl_file" == "back" ]] ; then
    	  clear
    	  build_exclusions
        elif [[ "$excl_file" == "2" || "$excl_file" == "Exit" || "$excl_file" == "exit" ]] ; then
    	  echo "Exiting..."
    	  exit
        elif [[ -e "$HOME/.rescript/config/$excl_file-exclusions" ]] ; then
	  {
	  echo "# These are the default rescript exclusions for your home directory:"
	  echo "$HOME/.cache/*"
	  echo "$HOME/.local/share/Trash/*"
	  echo "$HOME/.rescript/lock/*"
	  echo "$HOME/.gvfs"
	  echo "$HOME/.dbus"
	  echo "$HOME/.local/share/gvfs-metadata"
	  echo "$HOME/.Private"
	  echo "$HOME/.Trash"
	  echo "$HOME/.cddb"
	  echo "$HOME/.aptitude"
	  echo "$HOME/.adobe"
	  echo "$HOME/.bash_history"
	  echo "$HOME/.dropbox"
	  echo "$HOME/.dropbox-dist"
	  echo "$HOME/.macromedia"
	  echo "$HOME/.xsession-errors"
	  echo "$HOME/.recently-used"
	  echo "$HOME/.recently-used.xbel"
	  echo "$HOME/.local/share/recently-used*"
	  echo "$HOME/.thumbnails/*"
	  echo "$HOME/.Xauthority"
	  echo "$HOME/.ICEauthority"
	  echo "$HOME/.gksu.lock"
	  echo "$HOME/.pulse"
	  echo "$HOME/.pulse-cookie"
	  echo "$HOME/.esd_auth"
	  echo "$HOME/.ecryptfs"
	  echo "$HOME/.mozilla"
	  echo "$HOME/.config/google-chrome"
	  echo "$HOME/.config/chromium"
	  echo "$HOME/.opera"
	  echo "$HOME/.npm"
	  echo "$HOME/.gnupg/rnd"
	  echo "$HOME/.gnupg/random_seed"
	  echo "$HOME/.gnupg/.#*"
	  echo "$HOME/.gnupg/*.lock"
	  echo "$HOME/.gnupg/gpg-agent-info-*"
	  echo "$HOME/.config/**/Cache"
	  echo "$HOME/.config/**/GPUCache"
	  echo "$HOME/.config/**/ShaderCache"
	  echo "$HOME/snap/**/.config/**/Cache"
	  echo "$HOME/snap/**/.config/**/GPUCache"
	  echo "$HOME/snap/**/.config/**/ShaderCache"
	  echo "$HOME/Downloads"
	  echo "*.lock"
	  echo "*.bak"
	  echo "*.backup"
	  echo "*.backup*"
	  echo "*~"
	  echo ""
	  echo "# Write your custom exclusions below:"
	  } > "$HOME/.rescript/config/$excl_file-exclusions"
	  clear
	  echo "Done building exclusion list for ["$excl_file"]."
	  build_exclusions
        else
	  clear
	  echo "There is no exclusion file called ["$excl_file"]; try again with the correct name."
	  build_exclusions
        fi
      elif [[ "$ans_excl" == "no" || "$ans_excl" == "n" || "$ans_excl" == "No" || "$ans_excl" == "N" || "$ans_excl" == "NO" ]] ; then
        clear
        echo "No changes made."
        build_exclusions
      fi
    else
      clear
      echo "There is no exclusion file called [$excl_file]."
      build_exclusions
    fi
  elif [[ "$excl_bld" == "2" || "$excl_bld" == "System" ||"$excl_bld" == "system" ]] ; then
    clear
    echo "======================"
    echo " Exclusion Files List "
    echo "======================"
    echo " [1] Back             "
    echo " [2] Exit             "
    echo "----------------------"    
    ls $HOME/.rescript/config | grep -e '-exclusions' | sed -e 's/\-exclusions$//'
    echo "======================"
    read -p "Type the name of the exclusion file you want to build or one of the options above [ 1 - 2 ]: " excl_file
    if [[ "$excl_file" == "1" || "$excl_file" == "Back" || "$excl_file" == "back" ]] ; then
      clear
      build_exclusions
    elif [[ "$excl_file" == "2" || "$excl_file" == "Exit" || "$excl_file" == "exit" ]] ; then
      echo "Exiting..."
      exit
    elif [[ -e "$HOME/.rescript/config/$excl_file-exclusions" ]] ; then 
      echo "This action will override your existing [$excl_file] exclusion file."
      read -p "Are you sure you want to proceed? y/n: " ans_excl
      if [[ "$ans_excl" == "yes" || "$ans_excl" == "y" || "$ans_excl" == "Yes" || "$ans_excl" == "Y" || "$ans_excl" == "YES" ]] ; then
        if [[ -e "$HOME/.rescript/config/$excl_file-exclusions" ]] ; then
	  {
	  echo "# These are the default rescript exclusions for your system:"
	  echo "/home/*"
	  echo "/proc/*"
	  echo "/sys/*"
	  echo "/dev/*"
	  echo "/run/*"
	  echo "/mnt/*"
	  echo "/media/*"
	  echo "/etc/mtab"
	  echo "/var/cache/apt/archives/*.deb"
	  echo "lost+found/*"
	  echo "/tmp/*"
	  echo "/var/tmp/*"
	  echo "/var/backups/*"
	  echo ""
	  echo "# Write your custom exclusions below:"
	  } > "$HOME/.rescript/config/$excl_file-exclusions"
	  clear
	  echo "Done building exclusion list for ["$excl_file"]."
	  build_exclusions
        else
	  clear
	  echo "There is no exclusion file called ["$excl_file"]; try again with the correct name."
	  build_exclusions
        fi
      elif [[ "$ans_excl" == "no" || "$ans_excl" == "n" || "$ans_excl" == "No" || "$ans_excl" == "N" || "$ans_excl" == "NO" ]] ; then
        clear
        echo "No changes made."
        build_exclusions
      fi
    else
      clear
      echo "There is no exclusion file called [$excl_file]."
      build_exclusions
    fi
  elif [[ "$excl_bld" == "3" || "$excl_bld" == "Back" ||"$excl_bld" == "back" ]] ; then
    clear
    exclusion_menu
  elif [[ "$excl_bld" == "4" || "$excl_bld" == "Exit" ||"$excl_bld" == "exit" ]] ; then
    echo "Exiting..."
    exit
  else
    clear
    echo "No valid action indicated..."
    build_exclusions
  fi
}

# ============================================================== #
# Install & Update																							 #
# ============================================================== #
function install {
  if [[ -d "$HOME/bin" ]] ; then
    cp $(basename "$0") "$HOME/bin/$(basename "$0")"
    chmod 700 "$HOME/bin/$(basename "$0")"
    echo "The script was moved to "$HOME/bin" directory."
    exit
  elif [[ -d "$HOME/.local/bin" ]] ; then
    cp $(basename "$0") "$HOME"/.local/bin/$(basename "$0")
    chmod 700 "$HOME/.local/bin/$(basename "$0")"
    echo "The script was moved to "$HOME/.local/bin" directory."
    exit
  else
    echo "There is no [/bin] directory present in your "$HOME" directory."
    read -p "Do you wish to create a [/bin] directory? y/n: " installation
    if [[ "$installation" == "Yes" || "$installation" == "yes" || "$installation" == "y" || "$installation" == "YES" || "$installation" == "Y" ]] ; then
      mkdir -p "$HOME/.local/bin"
      cp $(basename "$0") "$HOME/.local/bin/$(basename "$0")"
      chmod 700 "$HOME/.local/bin/$(basename "$0")"
      echo "The script was moved to "$HOME/.local/bin" directory."
      exit
    elif [[ "$installation" == "No" || "$installation" == "no" || "$installation" == "n" || "$installation" == "NO" || "$installation" == "N" ]] ; then
      echo "Exiting..."
      exit
    else
      echo "No action indicated; exiting..."
      exit
    fi
  fi
}

function update {
	wget -O .rescript-latest https://gitlab.com/sulfuror/rescript.sh/raw/master/rescript 2> /dev/null

	if [[ "$(sed '3!d' $(which rescript))" == "$(sed '3!d' .rescript-latest)" ]] ; then
	  rm .rescript-latest
	  echo "You're already running the latest version!"
	  echo "$(rescript version)"
	else
	  chmod 755 .rescript-latest
	  read -p "$(./.rescript-latest version) is available; do you want to install it? (y/n):" updater
	  if [[ "$updater" == "y" || "$updater" == "Y" || "$updater" == "yes" || "$updater" == "YES" ]] ; then
  	  if [[ $(which rescript) == /usr/bin/rescript || $(which rescript) == /bin/rescript || $(which rescript) == /usr/local/bin/rescript ]] ; then
	      if [[ $USER == root ]] ; then
	        mv .rescript-latest $(which rescript)
	        echo "Rescript have been updated to the latest version!"
  	      echo "$(rescript version)"
	      else
	        rm .rescript-latest
	        echo "Rescript is located at $(which rescript)."
	        echo "To update in this location you need to run [update] again with [sudo]:"
  	      echo ""
	        echo "  sudo rescript udpate"
	        echo "" 
	        echo "Nothing done... exiting."
	        exit
  	    fi
	    else
	      chmod +x .rescript-latest
	      mv .rescript-latest $(which rescript)
  	    echo "Rescript have been updated to the latest version!"
	      echo "$(rescript version)"
	    fi
	  else
	    echo "Nothing done... exiting."
	    exit
	  fi
	fi
}

# ============================================================== #
# Commands Help																									 #
# ============================================================== #
function backup-help {
  echo "[backup] is for [backup] command in restic"
  echo ""
  echo "This command will take a new snapshot using the values set"
  echo "in your configuration file."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] backup"
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo "  -l, --log		This will create a log file with"
  echo "			the command output."
  echo ""
}

function cleanup-help {
  echo "[cleanup] is for [forget] and [prune] commands in restic"
  echo ""
  echo "This command will apply the [forget] policies set in your"
  echo "configuration file and then execute [prune] to actually"
  echo "delete the data that has been forgotten."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] cleanup [command_flag] [options]"
  echo ""
  echo "Command flags:"
  echo "  -d, --dry-run		Do not delete anything, just print"
  echo "			what would be done. This flag can"
  echo "			be used with any other restic flag"
  echo "			like: --host, --tag, --path"
  echo "			--group-by and any other flag and"
  echo "			option available but it must be"
  echo "			specified before restic options and"
  echo "			after [cleanup]."
  echo "  -e, --exec		This "special" flag can be used to"
  echo "			pass other restic flags like:"
  echo "			--host, --tag, --path, --group-by"
  echo "			and any other flag and option available"
  echo "			in restic but it will execute [prune]"
  echo "			at the end. This flag must be specified"
  echo "			before restic options and after [cleanup]."
  echo "  -n, --next		Display next scheduled; work only when"
  echo "			CLEANUP variable is set."
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo "  -l, --log		This will create a log file with"
  echo "			the command output."
  echo ""
  echo "[-d] and [-e] usage examples:"
  echo "  rescript [repo_name] cleanup -d --group-by tags"
  echo "	This will run the commands with [--dry-run], so it will not"
  echo "	delete anything"
  echo "  rescript [repo_name] cleanup -e --group-by tags"
  echo "	This will execute the commands, flags and options indicated"
  echo "	with [prune] at the end and IT WILL delete data"
  echo ""
}

function config-help {
  echo "[config] is an interactive command to make easy the to set up rescript"
  echo "configuration and exclusions files. You can create, edit, list"
  echo "and open your configuration and exclusions files."
  echo ""
  echo "Usage:"
  echo "  rescript config"
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

function editor-help {
  echo "[editor] is to select or change the default text editor"
  echo "to be used to open the rescript configuration and"
  echo "exclusion files. This will list the most common text editors"
  echo "used and also have an option to write the executable name"
  echo "of your favorite text editor if not listed."
  echo ""
  echo "Usage:"
  echo "  rescript editor"
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

function install-help {
  echo "[install] is to simply copy the script to your PATH directory"
  echo "inside your HOME. If there is no PATH in your HOME then rescript"
  echo "will ask you if you want to create one. If the answer is yes then"
  echo "it will create a [/bin] directory inside your [./local] directory."
  echo "If the answer is no then it will exit. If you don't want to use"
  echo "rescript from your PATH then remember to use it indicating the"
  echo "complete path where the script is located; if you have set another"
  echo "location for your PATH then just copy the script and put it there."
  echo ""
  echo "Usage:"
  echo "  rescript install"
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

function logger-help {
  echo "[-l|--log] is a flag used to make a log of your command."
  echo "This flag will create a log file of your desired command"
  echo "inside your rescript logs directory. This flag is intended"
  echo "to use only before commands, flags and options. You can"
  echo "use this flag and [-t|--time] at the same time."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] -l [command] [flag] [option]"
  echo "OR if you want to use [-t|--time] to log the duration too:"
  echo "  rescript [repo_name] -l -t [command] [flag] [option]"
  echo ""
}

function logs-help {
  echo "[logs] is for log files saved by rescript"
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] logs [command_flag]"
  echo "OR"
  echo "  rescript [repo_name] logs [command_flag] [logfile]"
  echo ""
  echo "Command flags:"
  echo "  -c, --cat		Display output of selected log file."
  echo "  -L, --list		List all log files saved."
  echo "  -r, --remove		Remove all log files."
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

function mounter-help {
  echo "[mounter] is to automatically mount your repository in your HOME"
  echo "directory. This will create a temporary directory where the"
  echo "repository will be mounted. After you quit the [mount] process"
  echo "the temporary directory will be removed."
  echo ""
  echo "Usage:"
  echo "  rescript mounter"
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

function random-check-help {
  echo "[checkout] is for [check --read-data-subset RANDOM/10] in restic"
  echo ""
  echo "This command will execute [check --read-data-subset]"
  echo "selecting a random number between 1-10 out of 10 groups."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] checkout"
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo "  -l, --log		This will create a log file with"
  echo "			the command output."
  echo ""
}

function restorer-help {
  echo "[restorer] is for [restore] command in restic"
  echo ""
  echo "This command will create a new directory in your "$HOME""
  echo "directory containing the restored files. The new directory will"
  echo "be named with a unique name so it will not conflict with your"
  echo "existing directories."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] restorer [command_flag] [host|path|snapshot ID|tag]"
  echo ""
  echo "Command flags:"
  echo "  -H, --host		Only consider snapshots for this host"
  echo "			when snapshot-ID is [latest]."
  echo "  -p, --path		Only consider snapshots which include"
  echo "			this [absolute] path for snapshot-ID [latest]."
  echo "  -s, --snapshot	Indicate snapshot-ID to restore."
  echo "  -T, --tag		Only consider snapshots which include this"
  echo "			taglist for snapshot-ID [latest]."
  echo ""
  echo "Global flags:"
  echo "  -h, --help		Display this help dialog."
  echo "  -l, --log		This will create a log file with"
  echo "			the command output."
  echo ""
}

function time-help {
  echo "[-t|--time] is a flag to take date, time and duration of commands."
  echo "This flag will create a small output between the command"
  echo "indicating the executed command for your repo, the date and time"
  echo "when the command began, when it ended and duration. This flag"
  echo "is intended to use only before commands, flags and options."
  echo "You can use this flag and [-l|--log] at the same time."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] -t [command] [flag] [option]"
  echo "OR if you want to use [-l|--log] to log the duration too:"
  echo "  rescript [repo_name] -t -l [command] [flag] [option]"
  echo ""
}

function unlocker-help {
  echo "[unlocker] is to remove the temporary lock created by rescript."
  echo "When rescript is running it will create a temporary lock file"
  echo "to prevent the interruption of other processes that could be active"
  echo "at the moment of executing another command within the same instance"
  echo "(e.g. scheduled jobs). If you are sure there are not any other"
  echo "processes running in the backgroup, then you can safely remove the"
  echo "created by rescript using this command."
  echo ""
  echo "Usage:"
  echo "  rescript [repo_name] unlocker"
  echo "Available flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

function update-help {
  echo "[update] is to update the rescript script itself."
  echo ""
  echo "Usage:"
  echo "  rescript update"
  echo ""
  echo "If script is located in /usr/bin:"
  echo "  sudo rescript update"
  echo ""
  echo "Available flags:"
  echo "  -h, --help		Display this help dialog."
  echo ""
}

# ============================================================== #
# Rescript Commands						 #
# ============================================================== #
if [[ ! "$1"  ]] ; then
  echo "You need to indicate the name of your repository or a"
  echo "command; type [rescript help] for usage."
  exit
elif [[ "$1" == "--log" || "$1" == "-l" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  logger-help
  exit
elif [[ "$1" == "--time" || "$1" == "-t" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  time-help
  exit
elif [[ "$1" == "backup" ]] ; then
  if [[ ! "$2" ]] ; then
    echo "You have not indicated any repo for ["$1"]..."
    echo ""
    backup-help
    exit
  elif [[ "$2" == "help" || "$2" == "--help" || "$2" == "-h" ]] ; then
    backup-help
    exit
  else
    echo "No valid option for for ["$1"]..."
    echo ""
    backup-help
    exit
  fi
elif [[ "$1" == "checkout" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  random-check-help
  exit
elif [[ "$1" == "cleanup" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  cleanup-help
  exit
elif [[ "$1" == "config" ]] ; then
  if [[ -z "$EDITOR" ]] ; then
    select_editor
    echo "Please type [rescript config] again to set/edit"
    echo "your configuration/exclusion files."
    exit
  fi
  if [[ "$2" == "--help" || "$2" == "-h" ]] ; then
    config-help
    exit
  else
    clear
    main_menu
    exit
  fi
elif [[ "$1" == "editor" ]] ; then
  if [[ "$2" == "--help" || "$2" == "-h" ]] ; then
    editor-help
    exit
  else
    select_editor
    exit
  fi
elif [[ "$1" == "help" || "$1" == "--help" || "$1" == "-h" ]] ; then
  if [[ ! "$2" ]] ; then
    echo "$usage"
    exit
  elif [[ "$2" == "backup" ]] ; then
    backup-help
    exit
  elif [[ "$2" == "checkout" ]] ; then
    random-check-help
    exit
  elif [[ "$2" == "cleanup" ]] ; then
    cleanup-help
    exit
  elif [[ "$2" == "config" ]] ; then
    config-help
    exit
  elif [[ "$2" == "editor" ]] ; then
    editor-help
    exit
  elif [[ "$2" == "install" ]] ; then
    install-help
    exit
  elif [[ "$2" == "logs" ]] ; then
    logs-help
    exit
  elif [[ "$2" == "mounter" ]] ; then
    mounter-help
    exit
  elif [[ "$2" == "restorer" ]] ; then
    restorer-help
    exit
  elif [[ "$2" == "unlocker" ]] ; then
    unlocker-help
    exit
  elif [[ "$2" == "update" ]] ; then
    update-help
    exit
  else
    echo "You have not indicated a valid option..."
    echo "$usage"
    exit
  fi
elif [[ "$1" == "install" ]] ; then
  if [[ "$2" == "--help" || "$2" == "-h" ]] ; then
    install-help
    exit
  else
    install
    exit
  fi
elif [[ "$1" == "logs" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  logs-help
  exit
elif [[ "$1" == "mounter" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  mounter-help
  exit
elif [[ "$1" == "restorer" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  restorer-help
  exit
elif [[ "$1" == "unlocker" ]] ; then
  echo "You have not indicated any repo for ["$1"]..."
  echo ""
  unlocker-help
  exit
elif [[ "$1" == "update" ]] ; then
  if [[ "$2" == "--help" || "$2" == "-h" ]] ; then
    update-help
    exit
  else
    update
    exit
  fi
elif [[ "$1" == "version" || "$1" == "--version" || "$1" == "-v" ]] ; then
  echo "rescript $version"
  exit
elif [[ ! -e "$HOME/.rescript/config/$1.conf" ]] ; then
  echo "There is no repo or command for ["$1"]. Indicate a valid"
  echo "repo or command name to proceed. Use [rescript help] for usage."
  exit
fi

# ============================================================== #
# Functions							 #
# ============================================================== #
source "$HOME/.rescript/config/$1.conf"
export RESTIC_PASSWORD="$RESTIC_PASSWORD"
export RESTIC_REPOSITORY="$RESTIC_REPO"
export B2_ACCOUNT_ID="$B2_ID"
export B2_ACCOUNT_KEY="$B2_KEY"
export AWS_ACCESS_KEY_ID="$AWS_ID"
export AWS_SECRET_ACCESS_KEY="$AWS_KEY"

# Set variables for functions
if [[ ! -z "$KEEP_LAST" && "$KEEP_LAST" -gt "0" ]] ; then
  FORGET_LAST="--keep-last $KEEP_LAST"
fi
if [[ ! -z "$KEEP_HOURLY" && "$KEEP_HOURLY" -gt "0" ]] ; then
  FORGET_HOURLY="--keep-hourly $KEEP_HOURLY"
fi
if [[ ! -z "$KEEP_DAILY" && "$KEEP_DAILY" -gt "0" ]] ; then
  FORGET_DAILY="--keep-daily $KEEP_DAILY"
fi
if [[ ! -z "$KEEP_WEEKLY" && "$KEEP_WEEKLY" -gt "0" ]] ; then
  FORGET_WEEKLY="--keep-weekly $KEEP_WEEKLY"
fi
if [[ ! -z "$KEEP_MONTHLY" && "$KEEP_MONTHLY" -gt "0" ]] ; then
  FORGET_MONTHLY="--keep-monthly $KEEP_MONTHLY"
fi
if [[ ! -z "$KEEP_YEARLY" && "$KEEP_YEARLY" -gt "0" ]] ; then
  FORGET_YEARLY="--keep-yearly $KEEP_YEARLY"
fi
if [[ ! -z "$KEEP_WITHIN" ]] ; then
  FORGET_WITHIN="--keep-within $KEEP_WITHIN"
fi
if [[ ! -z "$KEEP_TAG" ]] ; then
  FORGET_TAG="--keep-tag $KEEP_TAG"
fi
POLICIES=(
  $FORGET_LAST
  $FORGET_HOURLY
  $FORGET_DAILY
  $FORGET_WEEKLY
  $FORGET_MONTHLY
  $FORGET_YEARLY
  $FORGET_WITHIN
  $FORGET_TAG
)

if [[ ! -z "$HOST" ]] ; then
  RESTIC_HOST="--host $HOST"
fi
if [[ ! -z "$TAG" ]] ; then
  RESTIC_TAG="--tag $TAG"
fi

function automatic {
  LOG="$HOME/.rescript/logs/"$REPO"-log-$(date +%Y-%m-%d-%H:%M)"
  rescript-lock
  if [[ "$LOGGING" == "yes" || "$LOGGING" == "YES" || "$LOGGING" == "Y" || "$LOGGING" == "y" ]] ; then
    exec > >(tee -a "$LOG") 2>&1
  elif [[ "$LOGGING" == "no" || "$LOGGING" == "NO" || "$LOGGING" == "N" || "$LOGGING" == "n" ]] ; then
    echo > /dev/null
  fi
  echo -e "=========================================================================="
  echo -e "| - - - - - - - - > [ S T A R T I N G    B A C K U P ] < - - - - - - - - |"
  echo -e "=========================================================================="
  echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "$YELLOW""System:""$ENDCOLOR" "$(opsys)"
  if [[ "$HOST" ]] ; then
    echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOST"
  else
    echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
  fi
  if [[ "$DESTINATION" ]] ; then
    echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
  else
    echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$RESTIC_REPO"
  fi
  echo -e "--------------------------------------------------------------------------"

  # Backup and exclusions
  echo -e "$YELLOW""[Taking a Snapshot...]""$ENDCOLOR"
  restic backup $BACKUP_DIR --verbose --exclude-caches --exclude-file="$EXCLUDES" $RESTIC_TAG $RESTIC_HOST

  EXCLUSIONS=$(grep -E -v -n -c '(^#|^\s*$|^\s*\t*#)' "$EXCLUDES")
  echo -e "$YELLOW""There are $EXCLUSIONS exclusion rules...""$ENDCOLOR"

  echo -e "--------------------------------------------------------------------------"
  # Snapshot List
  echo -e "$YELLOW""[Snapshots List...]""$ENDCOLOR"
  restic snapshots

  # Check and Clean Repo Based on User's Policy
  if [[ -f "$HOME/.rescript/config/"$REPO"-datefile" || "$CLEAN" -gt "0" ]]; then
    if [[ ! -f "$HOME/.rescript/config/"$REPO"-datefile" ]] ; then
      touch "$HOME/.rescript/config/"$REPO"-datefile"
    fi
    if [[ "$(uname -s)" == "Linux" || "$(uname -s)" == "GNU" ]] ; then
      NOW=$(date +"%s")
      NEXT=$(date -f "$HOME/.rescript/config/"$REPO"-datefile" "+%s")
    elif [[ "$(uname -s)" == "Darwin"* || "$(uname -s)" == "FreeBSD"* ]] ; then
      NOW=$(gdate +"%s")
      NEXT=$(gdate -f "$HOME/.rescript/config/"$REPO"-datefile" "+%s")
    fi
    if [[ "$NOW" -lt "$NEXT" ]] ; then
      cleanup-next
    else 
      if [[ ! -z "$POLICIES" ]] ; then
        echo -e "$YELLOW""[Cleaning Repo...]""$ENDCOLOR"
        restic forget "${POLICIES[@]}"
        restic prune
        echo -e "$YELLOW""[Checking for Errors in Repo...]""$ENDCOLOR"
        restic check --cleanup-cache
        if [[ "$CLEAN" -gt "0" ]] ; then
          if [[ "$CLEAN" == "1" ]] ; then
            D="day"
          else
            D="days"
          fi
          echo -e "$YELLOW""[Done Cleaning; Next Cleanup and Check Will Be Done in $CLEAN $D...]""$ENDCOLOR"
          if [[ "$(uname -s)" == "Linux" || "$(uname -s)" == "GNU" ]] ; then
            date -d now+"$CLEAN"days > "$HOME/.rescript/config/"$REPO"-datefile"
          elif [[ "$(uname -s)" == "Darwin"* || "$(uname -s)" == "FreeBSD"* ]] ; then
            gdate -d now+"$CLEAN"days > "$HOME/.rescript/config/"$REPO"-datefile"
          fi
        fi
      fi
    fi
  else 
      if [[ ! -z "$POLICIES" ]] ; then
        echo -e "$YELLOW""[Cleaning Repo...]""$ENDCOLOR"
        restic forget "${POLICIES[@]}"
        restic prune
        echo -e "$YELLOW""[Checking for Errors in Repo...]""$ENDCOLOR"
        restic check --cleanup-cache
      fi
  fi

  # Stats
  echo -e "--------------------------------------------------------------------------"
  echo -e "$YELLOW""[Original Size for Latest Snapshot...]""$ENDCOLOR"
  restic stats --host "" latest
  echo -e "$YELLOW""[Deduplicated Size for Latest Snapshot...]""$ENDCOLOR"
  restic stats --mode raw-data --host "" latest
  echo -e "$YELLOW""[Original Size for All Snapshots...]""$ENDCOLOR"
  restic stats
  echo -e "$YELLOW""[Deduplicated Size for All Snapshots...]""$ENDCOLOR"
  restic stats --mode raw-data
  # Time and Runtime
  echo -e "--------------------------------------------------------------------------"
  echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
  echo -e "=========================================================================="
  echo -e "| - - - - - - - - - > [ B A C K U P      E N D E D ] < - - - - - - - - - |"
  echo -e "=========================================================================="

  if [[ "$CLEAN" -gt "0" && -z "$POLICIES" ]] ; then
    if [[ "$CLEAN" == "1" ]] ; then
      D="day"
    else
      D="days"
    fi
    echo "[rescript] noted that your CLEAN variable is $CLEAN, so [rescript] assumes that"
    echo "you want to perform a 'cleanup' (forget, prune and check) every $CLEAN $D but"
    echo "it can't execute it if you have not set the KEEP variables; please set your"
    echo "desired KEEP values in order to perform the 'cleanup' every $CLEAN $D. If you"
    echo "don't want [rescript] to 'cleanup' your repo automatically every $CLEAN $D,"
    echo "just leave the CLEAN variable blank in your cofiguration file and this"
    echo "message will not appear again."
    echo ""
    echo "For more info about this subject:"
    echo "https://gitlab.com/sulfuror/rescript.sh/blob/master/README.md#usage"
  fi
}

function backup {
  rescript-lock
  if [[ "$FLAGS" ]] ; then
    if [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
      backup-help
      exit
    elif [[ "$FLAGS" == "--log" || "$FLAGS" == "-l" ]] ; then
      echo "You must use [$FLAGS] only before any other command."
      echo ""
      logger-help
      exit
    else
      echo "Invalid flag ["$FLAGS"]..."
      echo ""
      backup-help
      exit
    fi
  fi
  echo -e "=========================================================================="
  echo -e "| - - - - - - - - > [ S T A R T I N G    B A C K U P ] < - - - - - - - - |"
  echo -e "=========================================================================="
  echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "$YELLOW""System:""$ENDCOLOR" "$(opsys)"
  if [[ "$HOST" ]] ; then
    echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOST"
  else
    echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
  fi
  if [[ "$DESTINATION" ]] ; then
    echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
  else
    echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$RESTIC_REPO"
  fi
  echo -e "--------------------------------------------------------------------------"
  restic backup $BACKUP_DIR --verbose --exclude-caches --exclude-file="$EXCLUDES" $RESTIC_TAG $RESTIC_HOST
  echo -e "--------------------------------------------------------------------------"
  echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
  echo -e "=========================================================================="
  echo -e "| - - - - - - - - - > [ B A C K U P      E N D E D ] < - - - - - - - - - |"
  echo -e "=========================================================================="
}

function cleanup {
  rescript-lock
  if [[ "$FLAGS" ]] ; then
    if [[ "$FLAGS" == "--dry-run" || "$FLAGS" == "-d" ]] ; then
      restic forget "${POLICIES[@]}" --dry-run $OPT
      echo "Using [--dry-run] flag does not remove anything."
      exit
    elif [[ "$FLAGS" == "--exec" || "$FLAGS" == "-e" ]] ; then
      echo -e "=========================================================================="
      echo -e "|- - - - - - - - > [ S T A R T I N G    C L E A N U P ] < - - - - - - - -|"
      echo -e "=========================================================================="
      echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
      echo -e "$YELLOW""System:""$ENDCOLOR" "$(opsys)"
      if [[ "$HOST" ]] ; then
        echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOST"
      else
        echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
      fi
      if [[ "$DESTINATION" ]] ; then
        echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
      else
        echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$RESTIC_REPO"
      fi
      echo -e "--------------------------------------------------------------------------"
      restic forget "${POLICIES[@]}" $OPT
      restic prune --cleanup-cache
      echo -e "--------------------------------------------------------------------------"
      echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
      echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
      echo -e "=========================================================================="
      echo -e "| - - - - - - - - - > [ C L E A N U P    E N D E D ] < - - - - - - - - - |"
      echo -e "=========================================================================="
      exit
    elif [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
      cleanup-help
      exit
    elif [[ "$FLAGS" == "--log" || "$FLAGS" == "-l" ]] ; then
      echo "You must use [$FLAGS] only before any other command."
      echo ""
      logger-help
      exit
    elif [[ "$FLAGS" == "--next" || "$FLAGS" == "-n" ]] ; then
      if [[ -z "$CLEAN" || "$CLEAN" -lt "1" ]] ; then
        echo -e "$YELLOW""You have not indicated any policy for the CLEAN value...""$ENDCOLOR"
        echo "The scrip will run check, forget and prune every time it runs"
        echo "unless you change the CLEAN variable at the beginning of this script."
        echo "The number indicated in the CLEAN variable must be in days."
        echo "For more information about the usage check out the following link:"
        echo "https://gitlab.com/sulfuror/rescript.sh/blob/master/README.md#usage"
        exit
      else
        cleanup-next
        exit
      fi
    else
      echo "Invalid flag ["$FLAGS"]..."
      echo ""
      cleanup-help
      exit
    fi
  fi
  if [[ ! -z "$POLICIES" ]] ; then
    echo -e "=========================================================================="
    echo -e "|- - - - - - - - > [ S T A R T I N G    C L E A N U P ] < - - - - - - - -|"
    echo -e "=========================================================================="
    echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
    echo -e "$YELLOW""System:""$ENDCOLOR" "$(opsys)"
    if [[ "$HOST" ]] ; then
      echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOST"
    else
      echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
    fi
    if [[ "$DESTINATION" ]] ; then
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
    else
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$RESTIC_REPO"
    fi
    echo -e "--------------------------------------------------------------------------"
    restic forget "${POLICIES[@]}"
    restic prune --cleanup-cache
    if [[ -f "$HOME/.rescript/config/"$REPO"-datefile" || "$CLEAN" -gt "0" ]] ; then
      cleanup-next
    fi
    echo -e "--------------------------------------------------------------------------"
    echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
    echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
    echo -e "=========================================================================="
    echo -e "| - - - - - - - - - > [ C L E A N U P    E N D E D ] < - - - - - - - - - |"
    echo -e "=========================================================================="
  else
    echo -e "$YELLOW""You have not indicated any policy value...""$ENDCOLOR"
    echo "If you want to use [cleanup] option you need to set the [KEEP] variables."
    echo "For more information about the Usage check out the following link:"
    echo "https://gitlab.com/sulfuror/rescript.sh/blob/master/README.md#usage"
  fi
}

function cleanup-next {
  if [[ ! -f "$HOME/.rescript/config/"$REPO"-datefile" ]] ; then
    touch "$HOME/.rescript/config/"$REPO"-datefile"
  fi
  if [[ "$(uname -s)" == "Linux" || "$(uname -s)" == "GNU" ]] ; then
    NOW=$(date +"%s")
    NEXT=$(date -f "$HOME/.rescript/config/"$REPO"-datefile" "+%s")
  elif [[ "$(uname -s)" == "Darwin"* || "$(uname -s)" == "FreeBSD"* ]] ; then
    NOW=$(gdate +"%s")
    NEXT=$(gdate -f "$HOME/.rescript/config/"$REPO"-datefile" "+%s")
  fi
  RESULT=$((NEXT-NOW))
  DAYS=$((RESULT / 86400))
  HOURS=$(((RESULT / 3600) % 24))
  MINUTES=$(((RESULT / 60) % 60))
  if [[ "$DAYS" == "1" ]] ; then
    D="day"
  else
    D="days"
  fi
  if [[ "$HOURS" == "1" ]] ; then
    H="hour"
  else
    H="hours"
  fi
  if [[ "$MINUTES" == "1" ]] ; then
    M="minute"
  else
    M="minutes"
  fi
  if [[ "$DAYS" -gt "0" ]] ; then
    if [[ "$HOURS" -gt "0" ]] ; then
      echo -e "$YELLOW""Next cleanup and check in $DAYS $D, $HOURS $H and $MINUTES $M...""$ENDCOLOR"
    else
      echo -e "$YELLOW""Next cleanup and check in $DAYS $D and $MINUTES $M...""$ENDCOLOR"
    fi
  elif [[ "$HOURS" -gt "0" ]] ; then
    echo -e "$YELLOW""Next cleanup and check in $HOURS $H and $MINUTES $M...""$ENDCOLOR"
  elif [[ "$MINUTES" -gt "0" ]] ; then
    echo -e "$YELLOW""Next cleanup and check in $MINUTES $M...""$ENDCOLOR"
  else
    echo -e "$YELLOW""Repo will be cleaned and checked in the next run...""$ENDCOLOR"
  fi
}

function logs {
  if [[ ! "$FLAGS" ]] ; then
    echo "You have not indicated any option."
    echo ""
    logs-help
    exit
  elif [[ "$FLAGS" == "--cat" || "$FLAGS" == "-c" ]] ; then
    if [[ "$LOGFILE" ]] ; then
      cat $HOME/.rescript/logs/"$LOGFILE"
    else
      echo "No log file indicated..."
      exit
    fi
  elif [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
    logs-help
  elif [[ "$FLAGS" == "--list" || "$FLAGS" == "-L" ]] ; then
    if ls $HOME/.rescript/logs/"$REPO"-* 1> /dev/null 2>&1 ; then
      ls $HOME/.rescript/logs/ | grep -e "$REPO"
      echo ""
      echo "Your logs are saved at $HOME/.rescript/logs"
    else
      echo "There are no log files to list for ["$REPO"]."
    fi
  elif [[ "$FLAGS" == "--remove" || "$FLAGS" == "-r" ]] ; then
    if ls $HOME/.rescript/logs/"$REPO"-* 1> /dev/null 2>&1 ; then
      rm -rf $HOME/.rescript/logs/"$REPO"-*
      echo "Log files removed for ["$REPO"]."
    else
      echo "There are no log files to remove for ["$REPO"]." 
    fi
  else
    echo "Invalid flag ["$FLAGS"]..."
    echo ""
    logs-help
    exit
  fi
}

function logger {
  LOG="$HOME/.rescript/logs/"$REPO"-"$CMD"-log-$(date +%Y-%m-%d-%H:%M)"
  exec > >(tee -a "$LOG") 2>&1
}

function mounter {
  if [[ "$FLAGS" ]] ; then
    if [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
      mounter-help
      exit
    else
      echo "Invalid flag ["$FLAGS"]..."
      echo ""
      mounter-help
      exit
    fi
  fi
  rescript-lock
  mkdir "$RMOUNT"
  restic mount "$RMOUNT"
  rm -rf "$RMOUNT"
}

function random-check {
  if [[ "$FLAGS" ]] ; then
    if [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
      random-check-help
      exit
    elif [[ "$FLAGS" == "--log" || "$FLAGS" == "-l" ]] ; then
      echo "You must use [$FLAGS] only before any other command."
      echo ""
      logger-help
      exit
    else
      echo "Invalid flag ["$FLAGS"]..."
      echo ""
      random-check-help
      exit
    fi
  fi
  rescript-lock
  echo -e "$YELLOW""Starting [checkout] for ["$REPO"]...""$ENDCOLOR"
  echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "--------------------------------------------------------------------------"
  restic check --read-data-subset $(($RANDOM % 10 + 1))/10
  echo -e "--------------------------------------------------------------------------"
  echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
}

function rescript-lock {
  if [ -e "$LOCK" ]; then
    echo -e "WARNING: "$REPO" repo is already running..."
    echo -e "If you are sure "$REPO" is not running, type"
    echo -e " "
    echo -e "	rescript "$REPO" unlock"
    echo -e " "
    echo -e "This will remove the lock for "$REPO""
    exit
  fi
  touch "$LOCK"
  trap 'rm -rf "$LOCK"' INT QUIT TERM EXIT
}

function restorer {
  rescript-lock
  if [[ "$LOGGER" ]] ; then
    if [[ "$LOGGER" == "--log" || "$LOGGER" == "-l" ]] ; then
      echo "You must use [$LOGGER] only before any other command."
      echo ""
      logger-help
      exit
    else
      echo "Invalid flag ["$LOGGER"]..."
      echo ""
      restorer-help
      exit
    fi
  fi
  if [[ ! "$FLAGS" ]] ; then
    echo "You have not indicated any option..."
    echo ""
    restorer-help
    exit
  elif [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
    restorer-help
    exit
  elif [[ "$FLAGS" == "--host" || "$FLAGS" == "-H" ]] ; then
    RESTIC_RESTORE="$HOME/restore-latest-host-"$HPTS"_$(date +%s)"
  elif [[ "$FLAGS" == "--log" || "$FLAGS" == "-l" ]] ; then
    echo "You must use [$FLAGS] only before any other command."
    echo ""
    logger-help
    exit
  elif [[ "$FLAGS" == "--path" || "$FLAGS" == "-p" ]] ; then
    RESTIC_RESTORE="$HOME/restore-latest-by-path_$(date +%s)"
  elif [[ "$FLAGS" == "--tag" || "$FLAGS" == "-T" ]] ; then
    RESTIC_RESTORE="$HOME/restore-latest-tag-"$HPTS"_$(date +%s)"
  else
    RESTIC_RESTORE="$HOME/restore-ID-"$HPTS"_$(date +%s)"
  fi
  if [[ "$FLAGS" == "--host" || "$FLAGS" == "-H" || "$FLAGS" == "--path" || "$FLAGS" == "-p" || "$FLAGS" == --tag || "$FLAGS" == "-T" ]] ; then
    if [[ ! "$HPTS" ]] ; then
      if [[ "$FLAGS" == "--host" || "$FLAGS" == "-H" ]] ; then
        echo "No [host] indicated..."
        echo ""
        restorer-help
        exit
      elif [[ "$FLAGS" == "--path" || "$FLAGS" == "-p" ]] ; then
        echo "No [path] indicated..."
        echo ""
        restorer-help
        exit
      elif [[ "$FLAGS" == "--tag" || "$FLAGS" == "-t" ]] ; then
        echo "No [tag] indicated..."
        echo ""
        restorer-help
        exit
      fi
    fi
    echo -e "=========================================================================="
    echo -e "|- - - - - - - - > [ S T A R T I N G    R E S T O R E ] < - - - - - - - -|"
    echo -e "=========================================================================="
    echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
    echo -e "$YELLOW""System:""$ENDCOLOR" "$(opsys)"
    if [[ "$HOST" ]] ; then
      echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOST"
    else
      echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
    fi
    if [[ "$DESTINATION" ]] ; then
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
    else
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$RESTIC_REPO"
    fi
    echo -e "--------------------------------------------------------------------------"
    if [[ "$DESTINATION" ]] ; then
      echo -e "$YELLOW""Restoring latest snapshot for ["$HPTS"] from:""$ENDCOLOR" "$DESTINATION..."
    else
      echo -e "$YELLOW""Restoring latest snapshot for ["$HPTS"] from:""$ENDCOLOR" "$RESTIC_REPO"
    fi
    restic restore latest --target "$RESTIC_RESTORE" "$FLAGS" "$HPTS" --verify
    echo -e "--------------------------------------------------------------------------"
    echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
    echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
    echo -e "=========================================================================="
    echo -e "| - - - - - - - > [ R E S T O R E    C O M P L E T E D ] < - - - - - - - |"
    echo -e "=========================================================================="
  elif [[ "$FLAGS" == "--snapshot" || "$FLAGS" == "-s" ]] ; then
    if [[ ! "$HPTS" ]] ; then
      echo "No [snapshot ID] indicated."
      echo ""
      restorer-help
      exit
    fi
    echo -e "=========================================================================="
    echo -e "|- - - - - - - - > [ S T A R T I N G    R E S T O R E ] < - - - - - - - -|"
    echo -e "=========================================================================="
    echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
    echo -e "$YELLOW""System:""$ENDCOLOR" "$(opsys)"
    if [[ "$HOST" ]] ; then
      echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOST"
    else
      echo -e "$YELLOW""Hostname:""$ENDCOLOR" "$HOSTNAME"
    fi
    if [[ "$DESTINATION" ]] ; then
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$DESTINATION"
    else
      echo -e "$YELLOW""Backup Destination:""$ENDCOLOR" "$RESTIC_REPO"
    fi
    echo -e "--------------------------------------------------------------------------"
    if [[ "$DESTINATION" ]] ; then
      echo -e "$YELLOW""Restoring snapshot ID ["$HPTS"] from:""$ENDCOLOR" "$DESTINATION..."
    else
      echo -e "$YELLOW""Restoring snapshot ID ["$HPTS"] from:""$ENDCOLOR" "$RESTIC_REPO"
    fi
    restic restore "$HPTS" --target "$RESTIC_RESTORE" --verify
    echo -e "--------------------------------------------------------------------------"
    echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
    echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
    echo -e "=========================================================================="
    echo -e "| - - - - - - - > [ R E S T O R E    C O M P L E T E D ] <  -- - - - - - |"
    echo -e "=========================================================================="
  else
    echo "Invalid flag ["$FLAGS"]..."
    echo ""
    restorer-help
    exit
  fi  
}

function time-start {
  echo -e "$YELLOW""Starting ["$CMD"] for ["$REPO"]...""$ENDCOLOR"
  echo -e "$YELLOW""Date and Time:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "--------------------------------------------------------------------------"
}

function time-end {
  echo -e "--------------------------------------------------------------------------"
  echo -e "$YELLOW""End:""$ENDCOLOR" "$(date +%a\ %b\ %d\ %Y\ %r)"
  echo -e "$YELLOW""Duration:""$ENDCOLOR" "$(duration)"
}

function unlocker {
  if [[ "$FLAGS" ]] ; then
    if [[ "$FLAGS" == "--help" || "$FLAGS" == "-h" ]] ; then
      unlocker-help
      exit
    else
      echo "Invalid flag ["$FLAGS"]..."
      echo ""
      unlocker-help
      exit
    fi
  fi
  if [[ ! -e "$LOCK" ]]; then
    echo "No locks found..."
  else
    rm -rf "$LOCK"
    echo "Script unlocked..."
  fi
}

# ============================================================== #
# Call Commands and Functions					 #
# ============================================================== #
if [[ "$2" == "" ]] ; then
  automatic
  exit
elif [[ "$2" == "--log" || "$2" == "-l" ]] ; then
  if [[ ! "$3" ]] ; then
    echo "You have not indicated any command for [$2]..."
    echo ""
    logger-help
    exit
  elif [[ "$3" == "--time" || "$3" == "-t" ]] ; then
    if [[ "$4" == "backup" || "$4" == "checkout" || "$4" == "cleanup" || "$4" == "mounter" || "$4" == "restorer" ]] ; then
      echo "["$3"] is not available for ["$4"]..."
      echo ""
      echo "Since rescript commands provide output with duration,"
      echo "this flag is intended only for restic commands use."
      echo ""
      exit
    fi
    rescript-lock
    CMD="$4"
    logger
    time-start
    restic "${@:4}"
    time-end
  elif [[ "$3" == "backup" ]] ; then
    CMD="$3"
    logger
    backup
  elif [[ "$3" == "checkout" ]] ; then
    CMD="$3"
    logger
    random-check
  elif [[ "$3" == "cleanup" ]] ; then
    CMD="$3"
    FLAGS="$4"
    OPT="${@:5}"
    logger
    cleanup
  elif [[ "$3" == "restorer" ]] ; then
    CMD="$3"
    FLAGS="$4"
    HPTS="$5"
    LOGGER="$6"
    logger
    restorer
  else
    rescript-lock
    CMD="$3"
    logger
    restic "${@:3}"
  fi
elif [[ "$2" == "--time" || "$2" == "-t" ]] ; then
  if [[ ! "$3" ]] ; then
    echo "You have not indicated any command for [$2]..."
    echo ""
    time-help
    exit
  elif [[ "$3" == "--log" || "$3" == "-l" ]] ; then
    if [[ "$4" == "backup" || "$4" == "checkout" || "$4" == "cleanup" || "$3" == "mounter" || "$4" == "restorer" ]] ; then
      echo "["$2"] is not available for ["$4"]..."
      echo ""
      echo "Since rescript commands provide output with duration,"
      echo "this flag is intended only for restic commands use."
      echo ""
      exit
    fi
    rescript-lock
    CMD="$4"
    logger
    time-start
    restic "${@:4}"
    time-end
  elif [[ "$3" == "backup" || "$3" == "checkout" || "$3" == "cleanup" || "$3" == "mounter" || "$3" == "restorer" ]] ; then
    echo "["$2"] is not available for ["$3"]..."
    echo ""
    echo "Since rescript commands provide output with duration,"
    echo "this flag is intended only for restic commands use."
    echo ""
    exit
  else
    rescript-lock
    CMD="$3"
    time-start
    restic "${@:3}"
    time-end
  fi
elif [[ "$2" == "backup" ]] ; then
  CMD="$2"
  FLAGS="$3"
  backup
  exit
elif [[ "$2" == "checkout" ]] ; then
  CMD="$2"
  FLAGS="$3"  
  random-check
  exit
elif [[ "$2" == "cleanup" ]] ; then
  CMD="$2"
  FLAGS="$3"
  OPT="${@:4}"
  cleanup
  exit
elif [[ "$2" == "help" || "$2" == "--help" || "$2" == "-h" ]] ; then
  echo "$usage"
  exit
elif [[ "$2" == "logs" ]] ; then
  FLAGS="$3"
  LOGFILE="$4"
  logs
  exit
elif [[ "$2" == "mounter" ]] ; then
  FLAGS="$3"
  mounter
  exit
elif [[ "$2" == "restorer" ]] ; then
  FLAGS="$3"
  HPTS="$4"
  LOGGER="$5"
  restorer
  exit
elif [[ "$2" == "unlocker" ]] ; then
  FLAGS="$3"
  unlocker
  exit
else
  rescript-lock
  restic "${@:2}"
fi